### ISSUE TITLE
Accented chars in boat names

### ISSUE THREAD

**Issue by sbsrouteur** [v-l-m/vlm#1012]
Some do not show-up properly (centlémin for example).

**Comment by farangfrog** [comment]
Je ne sais pas si c'est lié, mais il y a un problème sur certains noms de courses : par exemple http://www.virtual-loup-de-mer.org/races.php?type=arrived&idraces=20150911

**Comment by sbsrouteur** [comment]
Pour ces courses, c'est un simple problème d'encodage. Qu'on règle facilement dans l'écran d'Admin (PS ces 3 courses là ne doivent plus poser de problèmes maintenant). Comme ce sont de vielles courses, c'est probablement dû à la façon dont elles ont été crées.

**Comment by sbsrouteur** [comment]
Idem pour le nom de bateau en fait. Pb d'encodage, la ressaisie règle le problème.

**Comment by sbsrouteur** [comment]
Fix with e987456778b89d1471dc0666e1872898c1a11ca8
