### ISSUE TITLE
Layout ecran téléphone

### ISSUE THREAD

**Issue by sbsrouteur** [v-l-m/vlm#1032]
Il manque une icone sur le bouton login dans la barre de menu quand on n'est pas connecté sur téléphone : 

![c2cfff40f503f73c698af5e3391606ec.png](https://tof.cx/images/2017/11/03/c2cfff40f503f73c698af5e3391606ec.png)

**Comment by ChrisCatta** [comment]
c'est l'icone connecter ou deconnecter, mais sur PC elle est exterieur au bouton qui a juste le texte.
je vais voir pour la faire rentrer dedans sur les pts ecrans

**Comment by ChrisCatta** [comment]
PR
