### ISSUE TITLE
color selection does handle alpha properly

### ISSUE THREAD

**Issue by sbsrouteur** [v-l-m/vlm#1053]
http://www.virtual-winds.org/forum/index.php?/topic/7641-vlm-20/&do=findComment&comment=279924

**Comment by ChrisCatta** [comment]
Slt,
ça me parait normal et même obligatoire de passer en RGBA si on touche à l'alpha en quoi cela est il gênant?
Sinon supprimer la gestion de l'alpha dans le colorPick

**Comment by sbsrouteur** [comment]
actually fixed in 4779c6b634a57cbb65357fafabcfc788c6aee429
