### ISSUE TITLE
Add reason for update in races table

### ISSUE THREAD

**Issue by sbsrouteur** [v-l-m/vlm#1077]
and publish in the raceinfo WS

**Comment by pzia** [comment]
On ne peut pas juste le croiser avec la table d'admin qui logue les
updates?

Le dim. 14 oct. 2018 à 09:21, sbsrouteur <notifications@github.com> a
écrit :

**Comment by sbsrouteur** [comment]
See 11fc716dd8b4022a7a503d754cda334a1156339f
