### ISSUE TITLE
Problème récuperation trace partielle

### ISSUE THREAD

**Issue by Frogeater29** [v-l-m/vlm#1088]
FT peut récupérer sur demande un extrait de trace pour l'installer en "fantome"
pour les bateaux "arrivés" pas de problème.
Pour les bateaux en course VLM limite la longueur de la récuperation à 48h. OK c'est normal pour eviter de tout saturer, ca a été longtemps debattu.

le problème c'est que si on demande seulement 24h entre 2 bornes, le résultat est emputé des 6 premières heures.
la commande envoyée par FT:
GET /ws/boatinfo/tracks.php?idu=31930&idr=190102&starttime=1552080106&endtime=1552166506 HTTP/1.1

1 er fichier les données du bateau ciblé avec un depart "deptime" à 1552080006

2 eme fichier, request et reponse de vlm, avec une trace qui commence à 1552151106

ce qui est bizarre, c'est que lorsque la trace est longue (plusieurs jours), la demande de 24h n'est pas tronquée.
![pb recup trace1](https://user-images.githubusercontent.com/11804336/54144630-637e9280-442c-11e9-985f-05b9a7a07054.jpg)
![pb recup trace2](https://user-images.githubusercontent.com/11804336/54144682-7ee99d80-442c-11e9-9534-7edac537ad04.jpg)

**Comment by sbsrouteur** [comment]
Début d'explication.
le WS tracks récupère les traces dans la table position (celle des position live de la course). Mais si cette dernière ne contient rien, alors une seconde requête est exécutée qui combine la table position, ainsi que la table hitspos (celle ou il y a les positions historisées).
On transfère périodiquement les données de plus de 48h vers la table histpos. 
Donc je suppute que si on requête la table table des positions alors qu'elle ne contient qu'un sous-ensemble des données requêtées, on n'obtient que ce qui est dans la table position.
Donc c'est un petit bug. 

Je pourrais changer le WS pour combiner position et histpos systématiquement, de façon à ne plus avoir ce souci (s'il est bien du à ma théorie ci-dessus).

On peut faire l'essai sur testing si tu as moyen assez facilement de reproduire le souci.

++

**Comment by pzia** [comment]
Il faudrait vérifier ce que renvoie le ws smarttrack, dont l'objectif était
de normaliser au maximum les périodes demandées pour pouvoir les mettre en
cache

Le sam. 30 mars 2019 à 21:37, sbsrouteur <notifications@github.com> a
écrit :

**Comment by sbsrouteur** [comment]
FT utilise smarttrack pour déterminer les dates à demander pour récupérer la trace ?

**Comment by Frogeater29** [comment]
Salut, FT utilise track, pas smarttrack.
Je peux faire des essais avec smarttrack, c'est facilement reproductible, il suffit de demander le début de la trace d'un bateau(24h) en course depuis plus de 24h.
Je fais ça quand je trouve 5mn.
A+

**Comment by pzia** [comment]
@sbsrouteur , tu peux mettre la config des constantes DEFAULT POSITION AGE et MAX POSITION AGE ?

@Frogeater29 : dans le principe, ce que tu décris devrait marcher effectivement.

**Comment by sbsrouteur** [comment]
config-defines.php:    define("DEFAULT_POSITION_AGE", 1 * 3600);
config-defines.php:    define("MAX_POSITION_AGE", 1 * 172800);

J'ai surtout vu que si la requête sur la table positoin renvoie au moins 1 ligne, on ne cherche pas dans histpos les lignes qui pourraient manquer. Mais si on demande les dernières 24h, il ne devrait pas y avoir de manque (ou du moins je ne comprend pas encore comment).

Mais en relisant deux post au dessus je vois que tu requête les premières 24h. Après plus de 24h de course. Ben voila tu as la source de ton problème ; 

Tu demandes les 24 premières heures de course au bout de 50h. La table des position a encore les positoin H courant à H-48. Donc on zappe les 2h qui sont passées dans la table d'historisation des positions.

**Comment by pzia** [comment]
c'était a priori l'intérêt de smart track :
- exposer directement par bloc les urls de cache statique
- ne pas avoir a réfléchir

au prix d'une mécanique d'appel multiples et donc de fusion des bout de traces en local

**Comment by sbsrouteur** [comment]
On peut clore ?
