### ISSUE TITLE
Add Cantabria flag to the game

### ISSUE THREAD

**Issue by manueldeljesus** [v-l-m/vlm#1094]
I would be very grateful if you could add the flag of Cantabria to the game. I attach it to the message.

Thank you very much for your help

![MiniBanderaCantabria](https://user-images.githubusercontent.com/2642961/58383062-535d6480-7fd2-11e9-8624-bea03bb4ff19.png)

**Comment by farangfrog** [comment]
Done under the name "Cantabria". Thank you for the flag!
