### ISSUE TITLE
Pb boatsitting Firefox

### ISSUE THREAD

**Issue by farangfrog** [v-l-m/vlm#1096]
Message d'Alexflo38 au comptoir : "la gestion du boat sitting (lorsque je clic sur l ID du copain (a gauche)) cela me bloque definitivement Firefox..... pas le souci sous chrome"

**Comment by sbsrouteur** [comment]
Ok, j'ai rien et personne d'autre ne se plaint. On va dire qu'il n'y pas de problème.
