### ISSUE TITLE
Create separate calendar feeds for different racetypes

### ISSUE THREAD

**Issue by farangfrog** [v-l-m/vlm#1100]
Les courses à record prennent trop de place sur le calendrier de la page d'accueil de VLM et il n'est apparemment pour l'instant pas possible de les séparer des autres courses sur la base du feed actuel (http://www.v-l-m.org/feed/races.ical.php).

**Comment by sbsrouteur** [comment]
De quoi as tu besoin? D'un param dans l'URL pour filtrer les permanentes? d'un marqueur dans l'ICAL pour les détecter et le filtrer? D'autre chose?

**Comment by farangfrog** [comment]
Un param dans l'URL serait parfait je pense.

**Comment by sbsrouteur** [comment]
tu as moyen de tester ça sur testing ou je dois le mettre direct sur neptune ?

**Comment by sbsrouteur** [comment]
c'est quoi l'url exacte actuelle?

**Comment by farangfrog** [comment]
je peux tester sur testing

**Comment by farangfrog** [comment]
http://www.v-l-m.org/feed/races.ical.php?lang=en

**Comment by sbsrouteur** [comment]
C'est online sur testing : 
https://testing.v-l-m.org/feed/races.ical.php?lang=en&RaceType=0 pour avoir les courses "en ligne"
https://testing.v-l-m.org/feed/races.ical.php?lang=en&RaceType=1 pour avoir les courses "Record"

L'ancienne URL sans le filtre RaceType renvoie tout le monde comme avant.

Si ça te va, je peux faire une maj instantanée sur Neptune.

++

**Comment by farangfrog** [comment]
Super merci. Pb de connexions hier soir, donc pas pu tester. Je fais ça ce soir.

**Comment by sbsrouteur** [comment]
> Super merci. Pb de connexions hier soir, donc pas pu tester. Je fais ça ce soir.

du coup ça va ou pas?

**Comment by farangfrog** [comment]
Les deux liens renvoient les permanentes.

**Comment by farangfrog** [comment]
en fait, il n'y a pas de course en ligne pour l'instant sur testing. J'ai essayé de prendre une vieille, de la copier en changeant les dates, mais ça plante :

`phpMyEdit error: Invalid SQL: [INSERT INTO `races` (`idraces`, `racename`, `started`, `deptime`, `startlat`, `startlong`, `boattype`, `closetime`, `racetype`, `firstpcttime`, `depend_on`, `qualifying_races`, `coastpenalty`, `bobegin`, `boend`, `maxboats`, `theme`, `vacfreq`, `UpdateReason`, `updated`) VALUES ('20190930', 'Ring of Fire #8: Jayapura - Yapen', '0', '1569872809', '-2567', '140774', 'boat_Class40v2', '1569959213', '0', '50', '', '', '900', '0', '0', '0', '0', '5', '', CURRENT_TIMESTAMP)] SQLSTATE[HY000]: General error: 1366 Incorrect integer value: '' for column 'depend_on' at row 1`

**Comment by sbsrouteur** [comment]
Hummpf, une autre version du bug de la copie de course. Je corrige ça et je te fais signe...

**Comment by sbsrouteur** [comment]
Bon j'ai fixé le phpMyEdit pour l'édition des courses. Puis j'ai mis à jour a lib/phpcommon que j'avais oublié l'autre soir.

Tu as donc un calendrier des courses en lignes qui a deux courses.

++

**Comment by farangfrog** [comment]
Pas de pb pour les courses à record. Mais rien ne s'affiche pour les courses en ligne.

**Comment by farangfrog** [comment]
mais c'est normal. les dates de cloture de la ligne étaient avant la date d'ouverture. En mettant les bonnes dates, c'est bon. merci !

**Comment by sbsrouteur** [comment]
Il faut changer le filtre temporel de sélection des courses de façon à afficher dans le flux toutes les courses dont la ligne de départ n'est pas fermée depuis au moins 7 jours. Le filtre actuel ne convient pas.
