### ISSUE TITLE
bandeau "page obsolète" sur http://v-l-m.org/create_player.php

### ISSUE THREAD

**Issue by farangfrog** [v-l-m/vlm#1114]
Lorsque un compte est créé, un email de validation est généré avec un lien vers http://v-l-m.org/create_player.php?createplayer=validate&... 

Cette page de l'ancienne interface a le bandeau "Cette ancienne page n'est plus maintenue. Mettez à jour vos liens vers la nouvelle interface", ce qui peut troubler la personne qui s'inscrit. C'est arrivé au moins une fois.

Est-il possible d'enlever le bandeau pour cette page, ou alors d'utiliser une nouvelle page de validation sur la nouvelle interface ?

**Comment by sbsrouteur** [comment]
Salut,

J'ai enlevé le bandeau de Neptune (même si le site n'est de toute façon
plus maintenu).

PS (dès fois que je n'aurai pas été  assez clair sur le sujet cet été). La
gestion complète du login était dans la dernière mise à jour que j'ai dû
annuler. Je ferai plus de mise à jour, il était temps pour moi de passer à
autre chose.

++
