### ISSUE TITLE
Vhost unstable synchronisé avec le trunk

### ISSUE THREAD

**Issue by pzia** [v-l-m/vlm#117]
**Reported by paparazzia on 29 Mar 2009 19:59 UTC**
tout est dans le titre.

Le risque est que les dveloppeurs ne testent pas / ne se relisent pas avant de commiter (ce qui m'arrive dj parfois...)

**Comment by pzia** [comment]
**Commented by paparazzia on 13 Apr 2009 16:09 UTC**
Si fm est OK, je peux faire ce que j'ai sur mon serveur,  savoir configurer sur le serveur de dev 2 vhosts "automatiques"
- trunk.testing.v-l-m.org
- prod.testing.v-l-m.org

avec un raffraichissement auto depuis le svn.

**Comment by pzia** [comment]
@sbsrouteur : si on mets sur testing un vhost unstable.testing.v-l-m.org raffraichi en automatique par git pull régulier, ça te servirait ?

**Comment by sbsrouteur** [comment]
pas indispensable tant qu'il n'y a pas plus de 1 dev...

donc incubator IMHO
