### ISSUE TITLE
Interface d'admin pour les courses à inscriptions bloquées

### ISSUE THREAD

**Issue by pzia** [v-l-m/vlm#241]
**Reported by paparazzia on 27 Oct 2009 05:34 UTC**
Cf. http://listes.virtual-loup-de-mer.org/sympa/arc/dev/2009-10/msg00147.html

**Comment by sbsrouteur** [comment]
Le lien est mort, donc sauf à retrouver ce que tu voulais, on va dire que c'est plus à l'ordre du jour.
