### ISSUE TITLE
Utiliser Meteorologic pour les gribs FR / SW / BE

### ISSUE THREAD

**Issue by pzia** [v-l-m/vlm#337]
**Reported by paparazzia on 13 Jun 2010 15:45 UTC**
http://www.meteorologic.net

et 

http://grib.meteorologic.net

Ca doit tre possible de discuter d'un partenariat avec eux, mais seulement quand on saura grer plusieurs sources de grib dans vlm-c

**Comment by sbsrouteur** [comment]
site dead :(
