### ISSUE TITLE
Autoriser les WS a tout passer par le content

### ISSUE THREAD

**Issue by pzia** [v-l-m/vlm#405]
**Reported by paparazzia on 12 Sep 2010 12:39 UTC**
De manire compatible avec le params=...

Le content ne contiendrait que du json.

il faut un get_ws_var() qui se dbrouille pour maintenir la compatibilit.

**Comment by sbsrouteur** [comment]
incubator? won't fix?

**Comment by pzia** [comment]
wontfix : ça passe par une API v2
