### ISSUE TITLE
L'affichage du nombre d'engagés sur le tableau de bord est 0/0 avant le départ

### ISSUE THREAD

**Issue by pzia** [v-l-m/vlm#480]
**Reported by paparazzia on 31 Oct 2010 08:49 UTC**
Une rgression qui doit venir des optimisations rcentes sur ce genre de calcul (?)

**Comment by pzia** [comment]
C'est toujours vrai ? ou un not a bug ?

**Comment by Phille** [comment]
En fait ce n'est pas le nombre d"engagés mais le ranking qui est 0/0 (normal puisque la course n'est pas encore partie).
Sinon je ne vois pas!?
![engage-0-01](https://cloud.githubusercontent.com/assets/11163172/6662300/218d2088-cbba-11e4-990c-e4dd6a9f9ced.JPG)

**Comment by pzia** [comment]
En fait, il faudrait juste tester si la course est partie ou non et afficher si non le nombre d'engagés, non ?

**Comment by Phille** [comment]
On a déjà le nombre d'engagé sur la "home" page:
![engage-0-02](https://cloud.githubusercontent.com/assets/11163172/6662619/ca4cf4a2-cbbd-11e4-9575-8059901d07ab.JPG)

**Comment by pzia** [comment]
OK, donc soit je n'affiche rien si la course n'est pas partie, soit le nombre d'inscription.

**Comment by Phille** [comment]
amha "rien" tant que la course n'est pas partie ;)
