### ISSUE TITLE
WS Access policy in apache header

### ISSUE THREAD

**Issue by pzia** [v-l-m/vlm#539]
**Reported by paparazzia on 9 Jan 2011 11:12 UTC**
De mme qu'il y a des directives silverlight,  on peut mettre dans les header apache des directives d'autorisation :

Header Set Access-Control-Allow-Origin "http://example.org"

Le but sera de permettre de tester un login de prod sur du js hberg par testing.

**Comment by pzia** [comment]
**Commented by paparazzia on 20 Apr 2011 20:09 UTC**
Les tests sur testing ne sont pas concluant... soit une incomprehension, soit une norme pas finalise...

**Comment by sbsrouteur** [comment]
won't fix? ou incubator?

**Comment by pzia** [comment]
A revoir quand quelqu'un se remettra à développer jvlm

**Comment by pzia** [comment]
A règler pour le chat et le service Bosh

**Comment by pzia** [comment]
Seems OK
