### ISSUE TITLE
Amélioration polaire bp5

### ISSUE THREAD

**Issue by pzia** [v-l-m/vlm#654]
**Reported by paparazzia on 8 Jan 2012 12:38 UTC**
Nous avons collect quelques donnes pendant la course pour pouvoir amliorer ventuellement la polaire.

Le fichier est joint.

**Comment by pzia** [comment]
**Commented by paparazzia on 8 Jan 2012 17:38 UTC**
J'ai r-attach les donnes en compresses au format zip.

Les donnes collectes viennent de l :

http://banquepopulaire.geovoile.fr/julesverne/2011/positions.asp?lg=fr

Le format est du csv.

time (epoc), mililong, mililat, boatspeed (BP5), cap (BP5), WindSpeed (VLM), WindHeading (VLM)

**Comment by pzia** [comment]
@Phille, je te propose de fermer ce ticket si on ne fait rien des données : http://dev.virtual-loup-de-mer.org/vlm/raw-attachment/ticket/654/collecte-bp5-2011.txt.zip

(Ou si on l'a déjà fait)

**Comment by Phille** [comment]
On va fermer, car pour l'instant on (RisAMer) travaille sur l'Imoca60.
On pourra toujours reprendre les infos plus tard si c'est nécessaire.

**Comment by pzia** [comment]
For the record : Pour les vieux tickets, j'ai gardé les pj mais elles ne
seront plus accessibles en ligne

**Comment by Phille** [comment]
OK ... pas de pb, je l'ai DL sur mon DD :)
J'ai vu que je l'avais déjà ...
