### ISSUE TITLE
Amélioration de l'upgrade des maps

### ISSUE THREAD

**Issue by pzia** [v-l-m/vlm#656]
**Reported by paparazzia on 9 Jan 2012 22:02 UTC**
La release 0.19 n'a pas fonctionn comme prvu pour clip_gshhs
- pas de mise  jour des .dat
- pas de vidage de cache.

il faut probablement faire des scripts par module qui permettent de prparer puis d'executer la release.

**Comment by sbsrouteur** [comment]
A clore non?

**Comment by pzia** [comment]
yep.
