### ISSUE TITLE
ranking : autoriser le chargement par bloc

### ISSUE THREAD

**Issue by pzia** [v-l-m/vlm#682]
**Reported by paparazzia on 14 Feb 2012 08:12 UTC**
Pour limiter la bp et amliorer la ractivit des interfaces

**Comment by pzia** [comment]
**Commented by paparazzia on 2 Dec 2012 15:49 UTC**
En complment, on devrait carrment le mettre en cache.

**Comment by sbsrouteur** [comment]
done
