### ISSUE TITLE
Accent non-reconnu dans "race instructions"

### ISSUE THREAD

**Issue by pzia** [v-l-m/vlm#696]
**Reported by Phille on 19 Feb 2012 13:25 UTC**
Voir photo en FJ

**Comment by pzia** [comment]
@Phille Tu as un exemple récent ?

**Comment by Phille** [comment]
Je me rappelle vaguement du pb ... mais n'était ce pas lors de l'import sur neptune qu'on avait ce pb?

**Comment by pzia** [comment]
Il faudrait un cas de test...

**Comment by sbsrouteur** [comment]
y a moyen de retrouver le fichier joint original? sinon cloture en attendant de le retrouver (IMHO)

**Comment by Phille** [comment]
le voici ... :)

![accent-error-01](https://cloud.githubusercontent.com/assets/11163172/6836774/d0a4636e-d345-11e4-827c-38b98f37d05e.png)
