### ISSUE TITLE
Le WS boatinfo ne renvoie pas le TFS

### ISSUE THREAD

**Issue by pzia** [v-l-m/vlm#714]
**Reported by sbs on 14 Apr 2012 10:23 UTC**
Le WS est sensé renvoyer un champs TFS : Time from Start, mais en fait ce champs n'est pas présent dans les données.

Il n'est donc pas possible de connaitre le temps de course d'un bateau sur une course  record s'il n'est pas parti à l'ouverture de la course.

**Comment by pzia** [comment]
Cette information est présente dans le ws tracks (champ starttime) : 

  if ($users->engaged == $idr) $starttime = max(intval($users->userdeptime), $starttime);

**Comment by pzia** [comment]
@sbsrouteur : wontfix, isn't it ?

**Comment by sbsrouteur** [comment]
Je trouve bizarre de devoir demander la trackinfo pour avoir une information de course.
D'autant que sur une course à record, la trace reprend l'ensemble des tentatives et non pas juste la dernière. Donc le starttime n'est pas cohérent avec le début de la trace.

**Comment by pzia** [comment]
si c'est juste le userdeptime, ça ne doit pas être compliqué à ajouter...

**Comment by sbsrouteur** [comment]
choisi le milestone sur lequel ça va tomber :)
