### ISSUE TITLE
Erreur lors de la génération de maps VLM

### ISSUE THREAD

**Issue by pzia** [v-l-m/vlm#726]
**Reported by sbs on 4 Aug 2012 12:21 UTC**
J'ai remarqu que depuis quelques temps, dans le routeur, certains bouts de cartes manquent. C'est en fait du  des fichiers "tiles" errons. J'ai donc mis en place un systme de reprise, mais non, une fois errone, la tuile n'a plus l'air de se regnrer.

Voici le contenu du fichier reu lors de la demande de DL:

Warning: mkdir(): Permission denied in /home/vlm/vlmcode/site/gshhstiles.php on line 30

Warning: readfile(cache/gshhstiles/6/13/22.png): failed to open stream: No such file or directory in /home/vlm/vlmcode/site/gshhstiles.php on line 47

C'est pour la tile Zoom 6 X: 13 Y: 22

Si je demande le mme bout de carte depuis FT le problme ne se produit pas.

**Comment by pzia** [comment]
**Commented by sbs on 4 Aug 2012 12:25 UTC**
PS : je suis sur testing pour le moment, mais j'ai remarqu le pb des tiles qui manquent aussi en prod. Apparement tous les fichies invalides viennent de testing

**Comment by pzia** [comment]
**Commented by sbs on 4 Aug 2012 12:31 UTC**
En prod le service fonctionne correctement.

**Comment by pzia** [comment]
Pas un pb en production, sans doute un pb de droits, donc...

**Comment by sbsrouteur** [comment]
depuis la 0.35 le routeur stock les tiles en BD et il n'y a plus ce problème....
