### ISSUE TITLE
bug dans les cartes VLM

### ISSUE THREAD

**Issue by pzia** [v-l-m/vlm#738]
**Reported by sbs on 15 Dec 2012 15:43 UTC**
Si on zoom 10 ou mieux sur la zone de sibrie qui est  180W/E, on peut voir des artfacts lis  l'antmridien dans la rprsentation des montagnes.

**Comment by pzia** [comment]
**Commented by paparazzia on 22 Dec 2012 19:40 UTC**
Effectivement, il y a des artefacts.
Je joins un screenshot pour steph et spifou

**Comment by pzia** [comment]
Je ne le reproduis plus.

**Comment by sbsrouteur** [comment]
Effectivement le bug s'est auto-cicatrisé :)
