### ISSUE TITLE
Passage ligne et échouement

### ISSUE THREAD

**Issue by pzia** [v-l-m/vlm#750]
**Reported by Phille on 26 May 2013 12:52 UTC**
Le pb d'chouement aprs passage de la ligne d'arrive n'est pas encore resolu!
Pourriez-vous jeter un coup d'oeil svp

http://www.virtual-winds.org/forum/index.php/topic/7278-balade-celtique-nordique/?p=251273

**Comment by ylafon** [comment]
Je ferme ici, #788 est un dup mais a plus d'info.
