### ISSUE TITLE
Vitesse bateau versus distance parcourue sur 1 heure

### ISSUE THREAD

**Issue by pzia** [v-l-m/vlm#752]
**Reported by Phille on 21 Jul 2013 07:57 UTC**
Hello,
Je ne sais plus si j'avais dj mentionn ou pas ... mais ya souvent (presque toujours) un diffrence entre la Vitesse bateau et la distance parcourue pendant la dernire heure.
Voir photo en exemple.
la Vitesse bateau  varie entre 15.04 et 15.17 knts pendant la dernire heure et la distance parcourue est de 15.61 Nm ... d'o vient cette dif?

**Comment by sbsrouteur** [comment]
Est-ce qu'on peut fermer ce ticket ou il est toujours d'actualité. Le code semble sain pour cette fonction.

**Comment by Phille** [comment]
ya un bout de temps que je n'ai plus vérifié ...

**Comment by sbsrouteur** [comment]
on va dire que faute de cas reproduisant, on va clore. Il sera toujours temps de réouvrir si on a des suspiscions.
