### ISSUE TITLE
Check if update is required for MapArea when NSZ are used in a race

### ISSUE THREAD

**Issue by pzia** [v-l-m/vlm#764]
**Reported by sbs on 25 Jan 2015 21:08 UTC**
5/ la maparea est faite pour définir le zoom utilisé pour visionner les WP et IceGates via le tableau de bord VLM (tout en haut  droite)  et si les NSZ peuvent être visionnées de la même manière y faut une maparea.

**Comment by sbsrouteur** [comment]
Pas de maparea pour les NSZ.

won't fix.
