### ISSUE TITLE
Transformer toutes les références à dev.v-l-m.org vers github

### ISSUE THREAD

**Issue by pzia** [v-l-m/vlm#771]
Toutes les références doivent être modifiées pour que les amateurs de développements puissent nous trouver.

**Comment by pzia** [comment]
Si quelqu'un (@Phille ? ;)) passe par là, il faudrait remplacer l'url : http://dev.v-l-m.org/vlm ou http://dev.virtual-loup-de-mer.org/vlm dans http://wiki.v-l-m.org par http://v-l-m.github.io/vlm/

Thanks

**Comment by Phille** [comment]
OK, je m’en occupe ;)

Grtz,

Phille

**Comment by pzia** [comment]
y'a pas le feu non plus ;) (mais faudra le faire)

2015-02-26 18:37 GMT+01:00 Phille notifications@github.com:

**Comment by pzia** [comment]
:+1: Excellent le renseignement de ticket par mail :)

**Comment by Phille** [comment]
- [http://dev.virtual-loup-de-mer.org/vlm/report/1 Rapports de bugs]
- Aider à la [[Traduction]]
- [http://dev.virtual-loup-de-mer.org/vlm/ Coin des développeurs]
- [http://dev.virtual-loup-de-mer.org/vlmtools/ Coin des développeurs d'outils autour du jeu]

Remplacer les liens vlm par github donne des erreurs 404,  dans les exemples ci-dessus ! :-(

… et le coin des développeurs n’est pas connu !?

Quid ?

**Comment by pzia** [comment]
> - [http://dev.virtual-loup-de-mer.org/vlm/report/1 Rapports de bugs]

https://github.com/v-l-m/vlm/issues

> - [http://dev.virtual-loup-de-mer.org/vlm/ Coin des développeurs]

http://v-l-m.github.io/vlm/

> - [http://dev.virtual-loup-de-mer.org/vlmtools/ Coin des développeurs
>   d'outils autour du jeu]

=> ça n'existera plus (c'était de toute façon très peu utilisé).

Le mieux qu'on puisse faire c'est pointer sur la page Outils du wiki de dev
:
https://github.com/v-l-m/vlm/wiki/Outils

**Comment by Phille** [comment]
Je crois les avoir remplacé tous ... si vous en trouvez encore un faites moi signe :)
