### ISSUE TITLE
Import d'une course de testing sur neptune2 ne fonctionne pas

### ISSUE THREAD

**Issue by Phille** [v-l-m/vlm#774]
Comme demandé par papa: - tester l'ihm d'admin (import de course depuis testing)
j'ai fait 2 essais et à chaque fois j'au reçu une erreur :(  (voir image jointe)

![neptune2-import-error-01](https://cloud.githubusercontent.com/assets/11163172/6417520/300a50cc-beae-11e4-9b13-eec21c1166a7.PNG)

**Comment by pzia** [comment]
C'est la partie sur les NSZ qui ne marche pas, à regarder par @sbsrouteur ...

**Comment by sbsrouteur** [comment]
Avec les tables NSZ dans la base ça fonctionne beaucoup mieux ;)

Closed #774
