### ISSUE TITLE
Danger de Wingrid pour VLM ?

### ISSUE THREAD

**Issue by pzia** [v-l-m/vlm#780]
Je laisse @maitaivw et @oxygen77 développer...

**Comment by maitaivw** [comment]
En fait ce ws ne demande pas d'authentification VLM. C'est donc
extremement facile pour n'importe quelle autre application de
telecharger des zones vent de VLM. 

Ou de fomenter une attaque DOS, par exemple. 

Le 02-03-2015 07:55, paparazzia a écrit : 

> Je laisse @maitaivw [1] et @oxygen77 [2] développer... 
> 
> ## 
> 
> Reply to this email directly or view it on GitHub [3].

## Links:

[1] https://github.com/maitaivw
[2] https://github.com/oxygen77
[3] https://github.com/v-l-m/vlm/issues/780

**Comment by pzia** [comment]
Mais pas plus que des fichiers gribs de 33mo, non ?

**Comment by maitaivw** [comment]
C'est tres theorique bien sur.... Mais il me semble que le simple
telechargement ne fait que de l'IO sans passer par le moteur ni apache
ni aucun calcul, ce qui n'est pas le cas du ws qui consomme pas mal de
resources. 

Bon y'aurait d'autres moyens de toutes facon d'embeter le moteur, c'est
clair. 

Mais demander une authentification VLM ca serait p-tet pas plus mal non
(meme si bon, ca n'empeche rien) ? 

Le 02-03-2015 08:38, paparazzia a écrit : 

> Mais pas plus que des fichiers gribs de 33mo, non ? 
> 
> ## 
> 
> Reply to this email directly or view it on GitHub [1].

## Links:

[1] https://github.com/v-l-m/vlm/issues/780#issuecomment-76669448

**Comment by ylafon** [comment]
C'est surtout que ça devait etre fait en C au lieu de passer par du php... Je voulais faire un module apache pour ca, mais pas eu le temps de m'y pencher dessus...

**Comment by pzia** [comment]
Faut que je regarde, mais la majorité des appels doivent être mis en cache.
Je profiterai de Neptune 1 pour faire des benchmark.

L'authentification à mon avis ajouterai plus d'overhead qu'elle ne
protégerait réellement plus. Par contre pour la partie gribs de 33mo, ça a
du sens.

**Comment by maitaivw** [comment]
Pour info, pour les besoins de qtvlm, je demandais autant de "1000 points" que necessaire pour construire mon grib partiel (par exemple atlantique nord sur 5 jours). La conclusion etait que ca ne valait pas le coup, c'etait plus lent que de telecharger le grib mondial.

Sur une petite zone c'etait rentable, mais le principe du routage c'est evidement de voir ce qui se passe dans 3 ou 4 jours, et a la vitesse ou avance mon gp5 favori ca finit par faire du m² ;)

**Comment by pzia** [comment]
oui. Wingrid n'est pas adapté pour du routage long cour (il n'a pas été conçu pour ça.

La remarque valait plutôt pour ta remarque initiale (besoin lié au razkyu, qui lui me semble pouvoir être largement couvert par ce ws).
