### ISSUE TITLE
Service de type 'saildocs' pour fournir des gribs partiels

### ISSUE THREAD

**Issue by pzia** [v-l-m/vlm#781]
La demande est de pouvoir fournir des gribs partiels.

Quatres options à évaluer (potentiellement complémentaires) : 
1. des zones prédéfinies type "mer med" ou "Manche" produites automatiquement.
2. des zones paramètrables par les admins (désactivables)
3. des zones "automatiques" par course (genre on prendrait la zone de diagonale double de la plus grande distance entre 2 wp et qui est centrée sur le centre de gravité de la course)
4. des zones complètement libre à la demande de l'utilisateur.

Il y a des avantages aux 1, 2, et 3 car vlm ne calcule qu'une seule fois, et le résultat est cachable.

A vos claviers.

**Comment by sbsrouteur** [comment]
5/ wrapper les requetes NOAA correspondantes et mailer un URL avec le
fichier résultat une fois que c'est dispo. La NOAA fournit déjà ce service.

2015-03-02 8:00 GMT+01:00 paparazzia notifications@github.com:

**Comment by pzia** [comment]
Tu as un lien for the record ?

**Comment by sbsrouteur** [comment]
http://nomads.ncep.noaa.gov/cgi-bin/filter_gfs_0p50.pl?file=gfs.t06z.pgrb2full.0p50.f000&lev_10_m_above_ground=on&var_UGRD=on&va
r_VGRD=on&leftlon=0&rightlon=360&toplat=90&bottomlat=-90&dir=%2Fgfs.2015030206

**Comment by pzia** [comment]
@maitaivw et @oxygen77 : Conclusion ? Ca suffit comme service, ou vous pensiez à autre chose ?

**Comment by maitaivw** [comment]
Juste mon avis, comme j'ai deja dit c'est oxygen qui-sait-mieux concernant les scripts de ce genre...

Ca ne me convient pas trop un service qui renvoie un mail avec un grib en PJ. Ce qui me parait ideal c'est le telechargement  d'un extrait du grib VLM mondial, simplement limite a la selection du user en terme de dimensions geographiques. Si j'ai bien compris (et je sens que je vais me pencher sur ce sujet rapidement), c'est juste de la manipulation de records, sans interpolation ni aucun calcul savant.

**Comment by oxygen77** [comment]
Oui en effet, il faudrait que j'exhume le script que j'ai mais c'est bien l'idée. 

A l'époque je faisais ca sur le mode creation a l'avance d'un ensemble de sous-grib di grib monde selon le principe:
- telechargement sur noaa d'un fichier pour une horodate
- extraction des composantes vent
- concaténation au grib global en construction
- pour chaque sous-grib :
- découpage avec les coordonnées
- concaténation au sous-grib en construction. 

Tout ceci se fait ds un script Bash appelant les bin std de manipulation grib. 

Christophe

**Comment by sbsrouteur** [comment]
j'ai proposé cette option de mail parce que :
- L'API d'extraction partielle via HTTP existe déjà à la NOAA
- Le téléchargement de chaque bout prend un éternité car :
  - DL à 80kO/s max
  - Délai de 1 à 2s avant que chaque DL commence
  - Du coup la constitution d'un fichier de quelques jours prend trop longtemps pour que la requête http attende le résultat.

Je pensais plutot mailer une URL.

S'il y a un script qui fait déjà tout ça à partir du fichier 7J de VLM, pourquoi pas. Il faut voir combien de temps ça prend de faire tout ça, car il faudra supporter quelques centaines de requêtes en même temps lors des bascules météo.

En désyncrhronisant l'envoi de la requête, on peut même cacher les résultats. Genre le WS ne renvoie pas la zone exacte demandée, mais une un peu plus grande qui est alignée sur un pas de 5° par exemple. Du coup chaque demande est mise dans une queue de process, et on peut tuner combien de process tournent en //.
Du coup, si une zone a déjà été demandée on peut direct envoyer la réponses sans recalcul.

**Comment by maitaivw** [comment]
Oui, c'est exactement notre besoin, parce que charger un grib de 33mb en edge voire meme des fois en 3G c'est une misere et meme ca coute du forfait des fois... Et ce d'autant que depuis le chgt de NOAA zygrib est dans les choux completement.

Un detail il ne faut pas autoriser cette requete pdt l'interim, c'est inutile et penible a gerer en plus cote VLM.

**Comment by pzia** [comment]
pour @maitaivw et @oxygen77  :  Est ce que qtVlm sait charger plusieurs gribs disjoints ?
Je m'explique : 
- basiquement on peut faire ce que dit sbs, en prenant un arrondi à 5 10 ou 15° (voir plus bas).
- si on veut minimiser les recalculs de VLM, on peut aussi fournir à la demande des gribs en 5° par 5°, charge au client de les charger chacun. Du coup vraiment très cachable. Mais peut être que qt ne sait pas faire ça ?

Sur le pas, si on prends 15°, ça ne fait que ~115K minimum par zone (comparé au grib de 33Mo). Ca va ? ou faut encore plus petit (genre : arrondir à 5° qui fera qu'une zone fera au moins 15Ko, ou 10° qui fera qu'un fichier fera au moins 50K ).

Après, je veux bien que quelqu'un me sorte la ligne de commande qui va bien avec wgrib ou autre, et je ferai le reste...

**Comment by pzia** [comment]
Pas de réponse de @maitaivw et @oxygen77... 
Je sens que vous n'aimez pas charger plusieurs grib ;-)

**Comment by maitaivw** [comment]
Heu on sait charger 2 gribs a la fois, mais c'est pour gerer des donnees differentes (par exemple vent et vagues). 

Si on demandait 4 fichiers de 15° pour couvrir une zone de 60° Il faudrait qu'on les assemble nous memes, mais c'est tres faisable surtout qu'on est sur que les fichiers ont le meme format (type de donnees, step en temps et en espace).

Conclusion je vote OK pour une solution comme ca :) A voir si tous les gribs de 15° sont generes systematiquement et y'a qu'a connaitre l'url, ou si il faut faire une requete a vlm pour generer le "tile".

**Comment by sbsrouteur** [comment]
un service type smarttrack pour ça me semble la bonne solution non?

**Comment by pzia** [comment]
Oui pour un smartgrib : 
En entrée une zone
En sortie, une liste d'url vers des "bouts de gribs" disjoints.

**Comment by pzia** [comment]
Une bonne âme pour me donner la ligne de commande qui extrait une subregion d'un grib1 ?
En grib2, c'est http://www.cpc.ncep.noaa.gov/products/wesley/wgrib2/undefine.html

On utilise toujours les grib1 sur Vlm... donc wgrib en attendant que quelqu'un fasse la transition vers les grib2

**Comment by pzia** [comment]
J'utilisais ça à une époque : http://www.cpc.ncep.noaa.gov/products/wesley/ggrib.html
Toujours bon ? ou faisable avec wgrib2 directement ?

**Comment by ylafon** [comment]
wgrib2 a cette option:
-small_grib      out  X Y Z  make small domain grib file X=lonW:lonE Y=latS:latN Z=file (beta)
À tester, donc.

**Comment by pzia** [comment]
```
./wgrib2 ~/vlmdatas/gribs/latest.grb -small_grib 10:20 10:20 out.grb
grib1 message ignored (use wgrib)
```

Pfff... back to ggrib ou wgrib...

**Comment by pzia** [comment]
Bon, j'ai compilé ggrib depuis http://ftp.cpc.ncep.noaa.gov/wd51we/gribw/gribw.tar
Il est dans `~/bin/` sur testing.
un exemple : 

```
time ./ggrib ~/vlmdatas/gribs/latest.grb out.grb -15 45 0 60 
Wrote 34 records, skipped 0

real    0m0.067s
user    0m0.028s
sys 0m0.004s
```

Plutôt rapide, ça se cache en direct.

Le fichier généré en exemple est là : http://testing.v-l-m.org/out.grb si vous voulez vérifier. (OK dans qtvlm depuis mon mobile).

Je vais faire la partie cache... quand j'ai le temps

**Comment by sbsrouteur** [comment]
Il fair harder les grib2 qu'on recoir et concerti en grib1

## 

S Barthes

**Comment by pzia** [comment]
@sbs et @maitaivw : comment vous voulez gérer les points frontières (jonction de zone) ?
soit j'exclus les bords ouest et sud, soit ils sont mis systématiquement et il faudra faire gaffe en fusionnant les gribs...

@sbs : oui, grib1 donc ggrib

**Comment by Phille** [comment]
Est-ce que le "out.grb" est en 0.5° ou 0.25°? Car qtVlm me dit 0.5° mais ptet qu'il ne reconnait pas encore les 0.25°?
![grb025or05](https://cloud.githubusercontent.com/assets/11163172/7100870/4e931ada-e03a-11e4-97a7-6249a3ede729.JPG)

**Comment by sbsrouteur** [comment]
houlala le téléphone, mauvais clavier.

Il faut garder les grib2 qui arrivent de la NOAA et qu'on convertit en
Grib1 pour mettre à dispo dans VLM

++

**Comment by pzia** [comment]
@Phille : ce ticket ne traite pas du passage à 0.25, mais de la mise à disposition gracieuse de bout de gribs pour les beaux yeux de qtvlm :)

@sbsrouteur euh... c'est pas un autre ticket, ça ?

**Comment by maitaivw** [comment]
Sans les bords W et S moi ca me va, mais si c'est embetant c'est pas un gros soucis

**Comment by Phille** [comment]
yep ... mais j'avais compris que qtVlm voulait ça car sinon y fallait DL >120Mo sur un dumbphone!?
Donc ptet que tu faisais un essai avec grib partiel en 0.25°

**Comment by pzia** [comment]
Bon, les basiques sont en place : 
- une url (mise en cache) pour récupérer un carré de vent issu du grib
- un ws smargribs pour récupérer automatiquement la liste des urls correspondant à une zone.

Manque un peu de doc et quelques bricoles, mais l'essentiel y est.

**Comment by maitaivw** [comment]
Hello,

qtVlm sait maintenant re-assembler les grib-tiles en 1 seul grib. Tout baigne de ce cote-la, la mecanique de telechargement d'une zone fonctionne sur testing avec ces nouveaux ws.

Seul defaut mais de taille, les gribs "tiles" ne font que 2 jours en duree... C'est pke c'est sur testing?

Et sinon ca passe qd en prod?

Merci en tout cas, ca va bien soulager les telechargements sur les telephones...

**Comment by pzia** [comment]
2j côté testing.v-l-m.org c'est normal.

Pour la prod, euh, faut qu'on fasse le point :-)

**Comment by maitaivw** [comment]
Bon alors... c'est en prod, ca fonctionne nickel, c'est une révolution (vraiment)

Un détail me tarabuste néanmoins...

J'avais compris que si le tile etait deja généré, pas de redirection vers gribtiles.php, or j'ai systématiquement une redirection, meme si je demande 2 fois le meme tile unique.

Est-ce bien normal?

Ca donne ca dans ma console, systematiquement:

uncompressing network reply
redirected to "/gribtiles.php?south=45&west=-15&step=15&date=2015062312"
received "45/-15/2015062312.15.grb"
