### ISSUE TITLE
Paramètrage apache pour utiliser la RAM

### ISSUE THREAD

**Issue by pzia** [v-l-m/vlm#783]
Neptune2 a 16Go de RAM. On peut augmenter un peu la charge d'apache pour l'utiliser.

**Comment by sbsrouteur** [comment]
En pratique c'est quoi et ou  le paramétrage en question?

**Comment by pzia** [comment]
Dans `/etc/apache2/apache.conf`, les paramètres fixant le nombre de thread
/ de process / etc... Ouverts en parallèle.
C'est directement dépendant de la ram disponible.

**Comment by pzia** [comment]
Bon...
un process apache de vlm, c'est ~14Ko.
768*14K = presque 11Go
=> J'ai mis le maxclient et le server limit à 768 (avant c'était 256).

Ca me permet de garder de la marge pour InnoDb ou vlmc
