### ISSUE TITLE
SVN revision ID Mess

### ISSUE THREAD

**Issue by sbsrouteur** [v-l-m/vlm#786]
Vu sur testing : 
|   1156 | 2015-02-09 23:12:15 | 88.190.229.2   | site          |  3313 |
|   1157 | 2015-02-10 21:55:25 | 88.190.229.2   | site          |  3319 |
|   1158 | 2015-02-10 22:31:23 | 212.83.186.161 | site          |  3319 |
|   1159 | 2015-02-10 22:31:45 | 212.83.186.161 | moteur        |  3319 |
|   1160 | 2015-03-03 20:47:21 | 212.83.186.161 | site          |  3259 |
|   1161 | 2015-03-03 20:48:09 | 212.83.186.161 | site          |  3259 |
|   1162 | 2015-03-03 21:07:19 | 212.83.186.161 | site          |  3261 |
+--------+---------------------+----------------+---------------+-------+

On est revenu en arrière de 60 révisions entre le 10 février et aujourd'hui !!!! Je pense que c'est un effet de bord de la migration git, mais sinon la page module_status doit être reprise pour que ça fonctionne à nouveau. (sous réserve qu'on sache dire quelle est la révision qui va bien du coup).

PS j'ai pas regardé sur neptune

**Comment by maitaivw** [comment]
Ca fait peur, du coup 

Le 03-03-2015 22:17, sbsrouteur a écrit : 

> Vu sur testing : 
> | 1156 | 2015-02-09 23:12:15 | 88.190.229.2 | site | 3313 |
> | 1157 | 2015-02-10 21:55:25 | 88.190.229.2 | site | 3319 |
> | 1158 | 2015-02-10 22:31:23 | 212.83.186.161 | site | 3319 |
> | 1159 | 2015-02-10 22:31:45 | 212.83.186.161 | moteur | 3319 |
> | 1160 | 2015-03-03 20:47:21 | 212.83.186.161 | site | 3259 |
> | 1161 | 2015-03-03 20:48:09 | 212.83.186.161 | site | 3259 |
> | 1162 | 2015-03-03 21:07:19 | 212.83.186.161 | site | 3261 |
> +--------+---------------------+----------------+---------------+-------+ 
> 
> On est revenu en arrière de 60 révisions entre le 10 février et aujourd'hui !!!! Je pense que c'est un effet de bord de la migration git, mais sinon la page module_status doit être reprise pour que ça fonctionne à nouveau. (sous réserve qu'on sache dire quelle est la révision qui va bien du coup). 
> 
> PS j'ai pas regardé sur neptune 
> 
> ## 
> 
> Reply to this email directly or view it on GitHub [1].

## Links:

[1] https://github.com/v-l-m/vlm/issues/786

**Comment by pzia** [comment]
Ça ne m'étonne pas. Quand j'ai fait un test manuel, il y a des révisions qu'il n'arrivait pas à récupérer.

**Comment by sbsrouteur** [comment]
J'ai fait un check out et regardé le log, les numéro de révisions sont cohérents, mais il y en a moins que dans l'historique original visiblement. Je vais donc purger la table module stats vu qu'on n'a pas besoin de l'historique et on pourra clore.

On a perdu un partie de l'historique dans la bataille, mais il doit bien rester un backup du repo svn quelque part qu'on peut récupérer "okazou".

**Comment by pzia** [comment]
J'ai un backup, mais je pense que les révisions manquantes ont réellement
été perdues. Je vérifierai.
