### ISSUE TITLE
Tune cache for NSZ WS

### ISSUE THREAD

**Issue by sbsrouteur** [v-l-m/vlm#787]
default cache is one day, and is a pain when "tuning" NSZ with FT. Since FT cannot avoid silverlight from using the cache specification found in the returned WS header.

**Comment by pzia** [comment]
Ne manque t'il pas un paramètre (il existe peut-être) pour descendre le cache des ws globalement à 60seconde au max ? On activerai ce paramètre sur testing ? Ça doit être une ligne de code pour les ws qui utilisent la classe de base.

**Comment by Phille** [comment]
ça ne consomme pas trop de resources? car 60 secondes serait cool mais pas vraiment necessaire ... on est à 24h ... donc y a de la marge :)

**Comment by pzia** [comment]
60s sur testing, j'ai pas dit sur la prod ;-)

**Comment by sbsrouteur** [comment]
Pas de bol, j'ai pris comme modèle un vieux WS dans raceinfo qui n'utilise pas la classe de base WSBase.

Donc il faut reprendre les 3 lignes de code pour utiliser la classe de base et définir une durée de cache pour ce WS.

**Comment by Phille** [comment]
Hello ... ya un pb ... les NSZ ne sont PAS visible sur testing avec FT !?

**Comment by sbsrouteur** [comment]
Hummz, il est possible que les dernières modifs ont changé le format des
données retournées par le WS :(

Je regarderai demain si j'ai récupéré l'alim de mon PC portable.

**Comment by Phille** [comment]
c'est ok ... papa a corrigé ;)

**Comment by pzia** [comment]
@sbsrouteur : en principe, j'ai rien changé de tes 2 champs utiles.

**Comment by pzia** [comment]
Je rouvre le ticket car il mérite une discussion.

**Comment by sbsrouteur** [comment]
@paparazzia : Bon j'ai encore conflicté ce matin, car je trouve que c'est
mieu si on change légèrement la sémantique de la façon suivante :

// WS Caching defaults
define("WS_MIN_MAXAGE", 60);                  // Valeur mini de cache pour
un WS
define("WS_DEFAULT_CACHE_DURATION",24_3600);  // Valeur par défaut de cache
pour un WS
define("WS_NSZ_CACHE_DURATION",24_3600);      // Valeur par défaut du cache
pour le WS NSZ

Comme ça:
- on a une valeur min de cache pour éviter de surcharger neptune si on
  fait une fausse manip ailleurs dans un WS.
- on a une valeur par défaut à 24h ce qui me semblait plus ou moins être
  le cas avant, mais j'ai ptet pas compris un détail sur ce point.
- on a une valeur de cache réglable à par pour les NSZ, afin de pouvoir
  mettre 60s sur testing

Dans un second temps, on pourra tuner des valeurs de cache pas défaut pour
les autres WS. Pour faire bien il faudrait que la valeur par défaut de
cache NSZ reférence la valeur par défaut de tous les WS, mais je ne connais
pas la syntaxe: define("WS_NSZ_CACHE_DURATION",WS_DEFAULT_CACHE_DURATION);
??

++

**Comment by Phille** [comment]
serait-il possible d'avoir une valeur de cache par default de 3600 sur neptune2 ... FT ne peut forcer une maj du cache ... donc les modifs que j'ai fait sur les NSZ ne seront visible que dans 24h :(
une valeur par default de 3600 pour les NSZ serait déjà un bon pas en avant ;)

**Comment by pzia** [comment]
c'est déjà le cas en principe... (c'est mis à 60s, et c'est que je vois en test)

Erratum : tu parles de Neptune2... bon... va pour 3600... (mais pas plus ;))
Mais on peut forcer le cache avec &nocache

**Comment by Phille** [comment]
ça ne marche pas :(
maj de la NSZ sur VLM 13h06
vu par FT à 14h50 > toujours la situation AVANT la maj de la NSZ

![cache-reset-01](https://cloud.githubusercontent.com/assets/11163172/6652093/3cfee404-ca62-11e4-8878-58cbbd00c924.JPG)

![cache-reset-02-14h50](https://cloud.githubusercontent.com/assets/11163172/6652096/599cc932-ca62-11e4-8458-f92b24018b3a.JPG)

**Comment by pzia** [comment]
Ca doit être bon maintenant, j'ai vidé le cache serveur...

**Comment by Phille** [comment]
sorry, mais non ça marche pô.

**Comment by Phille** [comment]
on verra demain si ça marche ...

**Comment by pzia** [comment]
C'est coincé côté client. Maintenant le cache client est à 1h. Et aussi côté serveur.
Donc une fois que FT se sera débloqué, ça sera 1h.
La conséquence c'est qu'on aura plus de requêtes à traiter (mais c'est relatif).

FT pourrait implémenter un bouton pas trop accessible (pour éviter la tentation) qui passerait &nocache aux requêtes (dans les cas de ce genre). Une autre manière serait de changer la durée de cache suivant le moment de la course.

**Comment by Phille** [comment]
Ca marche, j'ai fait qq essais ... et cela a mis entre 5 minutes et 56 minutes avant que les changements soient visibles sur FT :)
