### ISSUE TITLE
Boat prefs (aka user_pref) for qtvlm & sbsrouteur

### ISSUE THREAD

**Issue by pzia** [v-l-m/vlm#792]
Il n'y a pas de pref prévu pour qtVlm : 
http://www.virtual-winds.org/forum/index.php/topic/6638-qtvlm/?p=263616

@maitaivw : c'est aux outils de se mettre d'accord sur des formats communs...
Les champs ne sont pas protégés (c'est juste un gentleman agreement d'utiliser conjointement les prefs)

**Comment by pzia** [comment]
Et c'est en ligne sur testing.

**Comment by maitaivw** [comment]
J'etais en train de taper la meme chose :)

Si je dois acceder a la zone pref de FT ou sbsrouteur ou reciproquement on se mettra d'accord bien sur.

On peut aussi imaginer une zone prefs commune aux outils pour communiquer.

Sinon on aurait droit a combien de giga par bateau? Je peux stocker n'importe quel format ou c'est du json forcement (ce qui est bien aussi) ?

**Comment by pzia** [comment]
je recommande de faire du json comme format de base, c'est plus cohérent.
Le champ est à 16Mo (oui, c'est très large).
Si on l'utilisait trop, il faudrait probablement que je le descende à 64K.
=> Donc je recommande de rester sous les 64K histoire de pas trop charger
la mulle

@sbsrouteur : tu veux le même champ ?

**Comment by maitaivw** [comment]
64k ca le fera, meme si conceptuellement ca serait mieux par bateau que par joueur.

**Comment by pzia** [comment]
c'est par bateau :)

**Comment by maitaivw** [comment]
Ah, super...

Mais faudrait changer le titre du ticket :)

**Comment by maitaivw** [comment]
Ca sera en prod la semaine prochaine c'est ca? Mardi?

**Comment by pzia** [comment]
oui, sauf si tu insistes pour l'avoir avant ;)

**Comment by maitaivw** [comment]
On avait jure qu'on ne faisait plus de modifs avant la release de qtvlm...

Mais c'est tentant :)

**Comment by pzia** [comment]
Ca me parait intéressant que vous expérimentiez pour vous et en liaison
avec d'autres outils.
Quitte à identifier des pref "communes" qu'on déclarerait comme telles par
la suite

**Comment by sbsrouteur** [comment]
@maitaivw : soit fort

2015-03-08 8:58 GMT+01:00 maitaivw notifications@github.com:

**Comment by maitaivw** [comment]
Puisqu'on parle d'echanges entres differentes choses:

Une idee (qui vaut p-tet un autre ticket, ou pas), ca serait d'avoir une zone commune aux bateaux d'une meme course pour un genre de shoutbox liee a la course. Libre aux outils de l'afficher ou pas. Pas online mais rafraichie qd le joueur fait sync et que la boite est affichee, avec donc la possibilite de poster un shout, style le comptoir de la taverne. 

Ca pose des pbs de moderation, donc c'est p-tet pas une si bonne idee que ca. Et p-tet meme d'autres problemes, qd on y pense :)

**Comment by maitaivw** [comment]
Hmm y'avait dans le wiki la syntaxe pour le set_prefs mais y'a plus... une bonne ame pour m'eviter de fouiller le code?

Je vois dans set_prefs.php un truc du style:
if (strlen($v)>255) $ws->reply_with_error("PREFS03", "With key=$k");

C'est normal?

**Comment by pzia** [comment]
https://github.com/v-l-m/vlm/wiki/WebServices

Effectivement il y a sans doute un truc à ajuster côté taille des données

**Comment by maitaivw** [comment]
Ok vu pour la syntaxe, merci

Pour la taille si je comprime 2K ca doit passer... mais 255 char ca le fait pas pour stocker une route.

**Comment by pzia** [comment]
A noter que tu dois normalement faire une requête en POST, mais vlm est tolérant (vu son api non normative et pas très REST ;))

**Comment by pzia** [comment]
en ligne sur testing
