### ISSUE TITLE
Chat inter boats

### ISSUE THREAD

**Issue by sbsrouteur** [v-l-m/vlm#793]
maitaivw commented 3 minutes ago
Puisqu'on parle d'echanges entres differentes choses:

Une idee (qui vaut p-tet un autre ticket, ou pas), ca serait d'avoir une zone commune aux bateaux d'une meme course pour un genre de shoutbox liee a la course. Libre aux outils de l'afficher ou pas. Pas online mais rafraichie qd le joueur fait sync et que la boite est affichee, avec donc la possibilite de poster un shout, style le comptoir de la taverne.

Ca pose des pbs de moderation, donc c'est p-tet pas une si bonne idee que ca. Et p-tet meme d'autres problemes, qd on y pense :)

**Comment by sbsrouteur** [comment]
Ce sujet m'interresse car je trouve que l'absence de chat interboat est un vrai manque pour l'interactivité en course.

On en a pas mal parlé avec @pzia, mais pour le moment on est encore au niveau du concept. L'idée serait de mettre en place un serveur xmpp pour gérer toute la messagerie. Ainsi il est possible de communiquer entre boats via les toolz, ou via vlm, ou via un outil de chat compatible xmpp.

La messagerie xmpp, dispose de toutes les fonctions dont il y a besoin :
- Message hors lignes
- Groupes (amis, courses, ...)
- Modération si necessaire ( ou ignore d'un boat)
- Comm "live"

Par contre, il faut que ce soit simple pour les joueurs, donc un auth intégrée dans le site vlm sans avoir besoin de faire de nouveau comptes avec adresse et tout le tintouin. Et donc une intégration dans les outils un peu plus simple car utilisation de l'auth intégrée vlm.

L'option tout faire à la main est plus simple au départ et plus rapide à mettre en œuvre, mais sera fonctionnellement super limitée (genre message texte court dans un dialogue) et toutes les autres fonctions seront à réinventer, donc à l'arrivée, sauf, à avoir quelqu'un de motiver pour pondre un gros paquet de code et le maintenir, probablement pas viable sur le long terme.

**Comment by maitaivw** [comment]
C'est sur que ca serait bcp mieux et viable comme ca. J'insiste neamoins sur le fait que la shoutbox doit etre 100% integree aux outils sans avoir besoin d'installer un logiciel ou un client en plus cote user, c'est un ws VLM et rien de plus vu du point de vue des outils.

Ca serait un gros plus de convivialite, c'est clair.

**Comment by oxygen77** [comment]
Au delà d'un ws pour récupérer des infos de compte ca pourrait être intégré via une lib ds les outils à nous de créer l'interface. 

Christophe

**Comment by pzia** [comment]
demander un ws pour faire une passerelle jabber... autant coder un truc quick'n dirty à la main...
il  y a des clients jabber qui sont très bien en C ou C++ ;)

J'ai un peu la même inquiétude que sbs : si on fait un truc spécifique, il faut prévoir toutes les fonctions de blacklistage, de préférence de joueurs, etc... dès lors qu'on voudrait faire des messages privés.
Donc en gros : 
- soit c'est du quick n dirty et c'est limité à des shootbox
- soit ça gère du message privé et il faut un truc jabber 

(ah, vu la réponse de @oxygen77 pendant que j'écrivais ce message, ça me va mieux)

**Comment by pzia** [comment]
Doc FTR 
- Converse JS : https://github.com/jcbrand/converse.js/releases
- Single Session support : https://github.com/candy-chat/xmpp-prebind-php
- Auth Mysql : https://code.google.com/p/prosody-modules/wiki/mod_auth_sql

**Comment by pzia** [comment]
pour info des dev d'outils, je suis parti sur une solution jabber.
Si vous me dites que qtVlm voire FT ne saura pas intégrer une lib jabber dans son code, on s'arrête et on réfléchi.

**Comment by maitaivw** [comment]
Pas de pbs insurmontables pour qtVlm, y'a des libs qui existent, au pire il faudra les porter en qt5 mais on a l'habitude ;)

**Comment by pzia** [comment]
Pour mémoire, mon suivi est là : https://github.com/v-l-m/vlm/wiki/Jabber

**Comment by pzia** [comment]
Le point : 
- en ligne sur testing un premier proto "fonctionnel"
- ce qui reste à faire marcher pour pouvoir mettre en prod. 
  - le proto utilise un proxy externe pour fonctionner : c'est pas viable en production.
  - avoir un annuaire des joueurs automatique (Cf. #798) pour faciliter l'ajout de contacts
- dans un premier temps, on pourra gérer la création des chats de courses "à la main"

Vous pouvez tester, ça s'active automatiquement sur testing quand vous vous logguez.

**Comment by Phille** [comment]
Ne parviens pas à m'inscrire.
C'est quoi le XMPP username (et son mdp)?

**Comment by pzia** [comment]
tu n'as pas besoin de t'inscrire : tu te loggues sur testing avec tes identifiants habituels.
En  bas à droite de l'écran, tu as un truc "Contacts", tu cliques et tu dois être loggué

EDIT : c'est mieux avec un navigateur moderne...

**Comment by Phille** [comment]
essais avec la dernière version de FF et de IE
pas moyen de s'inscrire  (je n'ai pas la possibilté "Contacts"), je n'ai que:
![vlm-chat-01](https://cloud.githubusercontent.com/assets/11163172/6655939/1f33e092-cb15-11e4-81d4-00b5d4a81f90.JPG)
et
![vlm-chat-02](https://cloud.githubusercontent.com/assets/11163172/6655940/2585b358-cb15-11e4-9090-3570501f72ce.JPG)

**Comment by pzia** [comment]
Comprends pas.
1/ Tu vas sur http://testing.v-l-m.org
2/ tu te connectes à vlm avec tes identifiants habituels (exemple test@virtual-winds.com / test), sur la mire d'authentification habituelle.
3/ tu es connecté, tu dois avoir le résultat suivant.
![capture du 2015-03-15 13 45 58](https://cloud.githubusercontent.com/assets/11092036/6656015/a3d3815a-cb19-11e4-9226-644db77f7c4d.png)

**Comment by Phille** [comment]
trouvé mon pb > j'utilisais testing.virtual-loup-de-mer.org au lieu de testing.v-l-m.org !
maintenant ça marche :)

**Comment by pzia** [comment]
ah, il va falloir que je le fasse marcher avec l'adresse longue, mais on verra plus tard...

**Comment by pzia** [comment]
@v-l-m/devs : ça prends bien forme maintenant.
Il me reste une bug à rêgler pour qu'on ne dépende pas d'un service tiers pour le chat.
Et j'ai une question existentielle sur les identifiants : 
- au départ, je pensais utiliser le "playername" (le nom de joueur qui s'affiche en haut à gauche)
  - mais nous y avons autorisé un peu tout (espace, signes de ponctuation...).
  - du coup cela ne permet pas de construire des identifiants jabber (playername@iridium.v-l-m.org par exemple).
- conséquence : la seule solution propre que je vois est d'utiliser l'identifiant du joueur (le player id, ou idp), qu'on représente souvent avec un @123 par opposition au boat qu'on représente avec un # 1234 

Est ce que ça vous parait acceptable ?
- pour le site, la boite de recherche afficherait bien le nom du joueur à sélectionner
- pour les outils, l'annuaire leur fournira à la fois l'id et le nom du joueur
- pour les clients lourds, et bien tant pis... Ce sera moins lisible.

L'alternative est de blinder les "nom de joueur" en supprimant espace et autres joyeuseté (ce qui est aussi possible, et peut être plus simple tout en restant lisible. Plus j'y pense, plus je préfère, mais je souhaite avoir votre avis.

**Comment by Phille** [comment]
un gars veut contacter un voisin de parcours, que voit-il sur la carte? Avec FT le pseudo-bateau et avec qtVlm il a fait un choix entre pseudo-bateau, nom bateau et N° ... donc je penche plutot pour "pseudo-bateau"

**Comment by pzia** [comment]
Ben, non, il y a plusieurs bateau par joueur, ça marchera pas.

J'ai déjà eu la discussion avec @sbsrouteur, le truc indispensable c'est un seul compte par joueur, sinon on revient 5 ans en arrière.

Après, il faut surement les fonctions d'annuaire amélioré, mais si on veut tout avoir d'un coup, ça marchera pas :)

**Comment by maitaivw** [comment]
On peut rajouter le pseudo du joueur (et pas du bateau) dans le tooltip du boat dans qtvlm, no pb. En indiquant que c'est ce contact pour le chat.

**Comment by Phille** [comment]
je vous suis ... mais il faut absolument un système qui permet de trouver facilement le compte du skipper que l'on veut contacter

**Comment by pzia** [comment]
Clic dans le classement sur le bateau. 
En haut à droite sur l'écran suivant

**Comment by pzia** [comment]
Je viens de tester en mobile, ça va une fois fermé le chat est pas trop intrusif

**Comment by pzia** [comment]
@maitaivw : si vous intégrez un client jabber dans qt, ce sera même juste un clic
@Phille : j'ai dans l'idée d'essayer de faire un clic to chat dans le classement, mais ce sera un ticket séparé.

**Comment by pzia** [comment]
Sinon, je vous confirme que ça marche à travers un proxy d'entreprise...

**Comment by pzia** [comment]
Petit test offline également : je viens de rallumer mon PC perso) et mon client jabber m'a affiché proprement le message suivant (envoyé cet après midi par le chat du site) : 
![capture du 2015-03-16 18 14 29](https://cloud.githubusercontent.com/assets/11092036/6671833/538d8052-cc08-11e4-9d12-d25e6b75bd6d.png)

Autre test fait à l'instant : envoi à 18:16 vers un contact OFF LINE
Ouverture du chat sur le site une minute après et : 
![capture du 2015-03-16 18 17 31r](https://cloud.githubusercontent.com/assets/11092036/6671949/2288a3fa-cc09-11e4-9647-655f43342883.png)

Donc ça a l'air de marcher pour l'offline.

Je vous envoi à @Phille et @sbsrouteur des messages offline maintenant, vous me direz si vous les avez quand vous vous logguerez sur testing.

**Comment by Phille** [comment]
ici c'est ok :)

![client-jabber-01](https://cloud.githubusercontent.com/assets/11163172/6672304/dc188b94-cc0b-11e4-92e1-42e141e138ef.JPG)

**Comment by pzia** [comment]
Sbs a confirmé aussi le offline

**Comment by pzia** [comment]
Sur l'identifiant jabber : je vous propose de partir sur le schéma suivant :
- ce sera (idp)@iridium.v-l-m.org
- la fonction d'ajout de contact acceptera les entrés suivantes :
  - texte qui recherche dans le nom du joueur 
  - @123 qui recherche sur la base du joueur 
  - #\123 qui recherche sur la base du bateau 
- la liste présentée portera le nom du joueur 
- un ws permettra aux outils de faire les mêmes recherches 

Ça ira ?

**Comment by pzia** [comment]
![capture du 2015-03-29 21 58 35](https://cloud.githubusercontent.com/assets/11092036/6887412/dbb13c34-d65e-11e4-9c34-455e8827894f.png)

Ca marche les avatars :) (en haut à gauche des fenêtres). Pas très utile mais bon ;)

**Comment by maitaivw** [comment]
Les rooms avec le numero de course comme title c'est un peu lourd non?

Et la derniere partie (vor6) je ne sais pas si c'est automatique ou pas mais y'a meme pas le titre de la course en subtitle...

**Comment by pzia** [comment]
@maitaivw c'est le ticket #805, et pour l'instant c'est manuel.

**Comment by Phille** [comment]
je n'ai plus le droit d'editer le nom d'un salon!? képassa?

**Comment by pzia** [comment]
J'ai rien changé

**Comment by Phille** [comment]
la barre menu ne contient pas la clef comme les autres salons
![knipsel](https://cloud.githubusercontent.com/assets/11163172/7481964/66efcb80-f374-11e4-9ed3-55456ce7fdbc.PNG)
