### ISSUE TITLE
Erreur sur testing (boatInfo)

### ISSUE THREAD

**Issue by maitaivw** [v-l-m/vlm#794]
Hello,

J'essaye de tester sur testing, et j'ai ca qd je fais boatInfo.php:

Notice: Undefined property: fullUsers::$userdeptime in /home/vlm/vlmcode/site/ws/boatinfo.php on line 47
suivi d'une erreur json qd j'essaye de decoder evidement.

**Comment by pzia** [comment]
Oups, je corrige avant le freeze de ce soir

**Comment by pzia** [comment]
Corrigé, en ligne sur testing. 
Fermer le ticket si OK

**Comment by Phille** [comment]
Ici ça marche … à maitai de confirmer :-)

**Comment by pzia** [comment]
For the record parce que mon commit a été fait avec smartphone : 
- c'est le commit 1ce609069ffb56a9a28b13eda61b59a90244409a
- et c'est liée au ticket #714

**Comment by maitaivw** [comment]
C'est tout bon, et le set_prefs fonctionne aussi... merci ;)
