### ISSUE TITLE
Impossible to create vlm account if email address ends with space

### ISSUE THREAD

**Issue by maitaivw** [v-l-m/vlm#795]
Tout est dans le titre, un ami qui essayait de creer son compte sur VLM sur son mobile en utilisant la saisie automatique de son appareil est systematiquement refuse a cause d'un espace a la fin de l'adresse email.

Il faudrait rajouter un trim avant de faire le controle. Meme chose sur le pseudo meme si ca passe avec des espaces a la fin, z'au cas-ou.

**Comment by pzia** [comment]
Est ce qu'il y a le même problème pour se logguer ?

**Comment by maitaivw** [comment]
Je viens d'essayer avec mon compte, pas de soucis au login si je mets un space a la fin de mon adresse email.

**Comment by pzia** [comment]
vu dans le code et en test.
je vais voir si on fait juste des modifs ciblées au moment de l'input, ou si on verouille le truc dans la classe

**Comment by pzia** [comment]
@mataivw : en ligne sur unstable.testing.v-l-m.org, à fermer si OK
