### ISSUE TITLE
Webservice de recherche de joueurs par nom (voire par nom de bateau) 

### ISSUE THREAD

**Issue by pzia** [v-l-m/vlm#798]
Pour la messagerie entre joueurs du ticket #793 il faut pouvoir ajouter un jabberid par une recherche simple sur le player name. 
Ce sera /ws/playerinfo/search.php?q=toto qui retournera une liste de joueurs avec nom, jid, id dont le nom contient q. 

On pourra l'étendre en incluant aussi les joueurs dont le nom d'un bateau réponds à la query string. 

Point d'attention : conversejs attends une simple liste d'objets alors que les ws habituels renvoie une information plus structurée. Il faudra ou bien le wrapper ou bien gérer un format spécifique.

**Comment by sbsrouteur** [comment]
WS avec auth? je pense que c'est mieux.

2015-03-12 7:10 GMT+01:00 paparazzia notifications@github.com:

**Comment by pzia** [comment]
Oui, mais probablement 2 ws (un "normal", et un dans le format attendu par conversejs.

**Comment by sbsrouteur** [comment]
Je pencherai pour un au format conversejs, pour le suivant c'est uniquement
s'il y a un besoin

**Comment by pzia** [comment]
oui, je vais me limite à ça. Après, je pense qu'il y a un besoin plus "générique" d'un ws/playerinfo/search pour trouver un joueur dans une course, ou avoir ceux qui ont tel flag, ou etc... mais ça attendra un autre ticket.

**Comment by pzia** [comment]
Donc probablement un path dédié à l'architecture chat et conversejs (#669) : 
- /jabber/search (Ce ticket)
- /jabber/prebind (Cf. #799)

Et par ailleurs, les ws "normaux" utilisés par les outils type #797 à leur place attendue.

Note pour plus tard : il faut aussi ajouter le jabberid dans playerinfo/profile.php

**Comment by pzia** [comment]
J'ai fait plus simple : dans playerinfo un service list et un list-converse similaire. 
Je garde le ticket le temps de décider du jabber id

**Comment by pzia** [comment]
Il manque probablement une normalisation des id jabber (passage en minuscule, recodage des espace en utf, etc..)
