### ISSUE TITLE
La table players_prefs est manquante

### ISSUE THREAD

**Issue by pzia** [v-l-m/vlm#800]
players_prefs

Ellle n'a pas été exportée depuis neptune... et personne n'a râlé...

=> Il faut la récupérer avant que @fmicaux ne ferme l'ancienne boutique.

**Comment by fmicaux** [comment]
Salut,

L'ancienne boutique fermera à la fin mars. (je vais demander sa 
résiliation avant le 20 pour qu'il ne soit pas renouvelé après le 31)

Ca ira ?

François

**Comment by pzia** [comment]
Sans problème, c'est l'affaire de 10 min ce week-end entre l'apéro et le resto :)

**Comment by pzia** [comment]
hop, exporté, importé... il manquait 4 tables en fait, mais pas trop utilisées : 
- players_prefs
- racetrophycontrol
- trophies
- users_Trophies

**Comment by sbsrouteur** [comment]
J'avais dans l'idée de remettre les trophies au gout du jour en ajoutant un
écran des classement supplémentaire sur la base de trophies. Mais après le
chat.
