### ISSUE TITLE
Preconfigurer un groupe de support 

### ISSUE THREAD

**Issue by pzia** [v-l-m/vlm#810]
Prosody permet de preconfigurer des groupes de contacts qui sont automatiquement ajoutés. 
Le cas le plus simple est d'avoir un support groupe ou on mettrait les go (Phille, Droopy...) 
Un peu plus touchy mais intéressant, un groupe boatsitter / boatsitté ou ces derniers apparaitraient automatiquement.

**Comment by pzia** [comment]
Pour le groupe de support, c'est simple à faire (un fichier texte qui liste les id).
Pour un groupe "dynamique" qui affiche les boatsitters, il faut faire un module prosody, mais c'est gérable. Un exemple ici : https://gist.github.com/jhass/948e8e8d87b9143f97ad#file-mod_diaspora_contacts-lua

**Comment by sbsrouteur** [comment]
Un groupe des GO c'est bien. Un groupe de BS, a priori c'est overkill car :
- Quand on BS c'est qu'on n'est pas la ou Dispo, donc pas de chat
- Si on peut faire un salon privé ça fournit la même chose et on a rien à
  gérer, les gens se débrouillent
- De temps à autres P&M s'invitent au sujet des courses en
  groupe/équipes, BS qui ne sont pas fair. Ne pas avoir de salon de BS
  évitera ce genre de discussions.

2015-03-17 6:32 GMT+01:00 paparazzia notifications@github.com:

**Comment by pzia** [comment]
Précision : ce ne sont pas des conferences, mais des "groupes de contacts".

L'intérêt que j'y voyais était de préconfigurer automatiquement des
contacts plausibles pour les joueurs.
