### ISSUE TITLE
Possible NSZ Major issue

### ISSUE THREAD

**Issue by sbsrouteur** [v-l-m/vlm#812]
When crossing AM, the segment used for the intersection goes across the globe instead of across the AM thuis creating false NSZ crossing.

To check with JMEME issue today

**Comment by Phille** [comment]
Ya eu 3 cas jusqu'à présent :(

(283) Checking user 9361: (race 141505) 
     Prev Hdg: 185.939 PIM=2/PIP=118.2/Heading=185.90443875564
    Position update (WSpd=14.4, WHdg=67, Hours=0.0831, ANG=118.2, Hdg=185.90443875564, BS=17.992, Dist=1.4943138146421nm) ... done
    Checking for coast crossing (vlm-c)
    Using: /home/vlm/vlmdatas/gshhs/gshhs_f.b

 Test basic segments intersections
1 0=0
2 1=1
3 R=-1
4 R=-1
6 R=-1
    **\* Processing exclusion zones (DB Loaded exclusion zone 141505)***
 -179997.96899482 -45297.179474301 179998.38806709 -45321.95257858 -150 -56 -130 -54
 -179997.96899482 -45297.179474301 179998.38806709 -45321.95257858 -130 -54 -125 -53
 -179997.96899482 -45297.179474301 179998.38806709 -45321.95257858 -125 -53 -120 -51
 -179997.96899482 -45297.179474301 179998.38806709 -45321.95257858 -120 -51 -115 -51
 -179997.96899482 -45297.179474301 179998.38806709 -45321.95257858 -115 -51 -110 -53
 -179997.96899482 -45297.179474301 179998.38806709 -45321.95257858 -110 -53 -105 -54.5
 -179997.96899482 -45297.179474301 179998.38806709 -45321.95257858 -105 -54.5 -100 -57.25
 -179997.96899482 -45297.179474301 179998.38806709 -45321.95257858 -100 -57.25 -75 -60
 -179997.96899482 -45297.179474301 179998.38806709 -45321.95257858 -75 -60 -70 -59
 -179997.96899482 -45297.179474301 179998.38806709 -45321.95257858 -70 -59 -65 -57.75
 -179997.96899482 -45297.179474301 179998.38806709 -45321.95257858 -65 -57.75 -60 -56.5
 -179997.96899482 -45297.179474301 179998.38806709 -45321.95257858 -60 -56.5 -55 -55
 -179997.96899482 -45297.179474301 179998.38806709 -45321.95257858 -55 -55 -50 -53.25
 -179997.96899482 -45297.179474301 179998.38806709 -45321.95257858 -50 -53.25 -45 -51
 -179997.96899482 -45297.179474301 179998.38806709 -45321.95257858 -45 -51 -40 -48
 -179997.96899482 -45297.179474301 179998.38806709 -45321.95257858 -40 -48 -35 -45 Intersection ratio 0.40138881409364

Intersection -179.99943071868 -45.307123144487
    **\* YES player 9361 CROSSED (vlmc), 
        Exclusion Zone has been crossed : 
            BOAT : -45.297179,-179.997969 <----> -45.321953,179.998388
            EncounterCoordinates -45.307123144487, -179.99943071868

GoogleMap http://maps.google.fr/maps?f=q&hl=fr&geocode=&q=-45.307123144487,-179.99943071868&ie=UTF8&spn=0.0191,0.082998&t=p&z=11&iwloc=addr. 

VLMMAP http://virtual-loup-de-mer.org/mercator.img.php?idraces=141505&lat=-45.297179474301&long=-179.99796899482&maparea=18&tracks=on&age=6&list=9361&x=1000&y=600&proj=mercator&text=right&seg1=-45.307123144487,-179.99943071868:-45.307123144487,-179.99943071868&seg2=-45.297179474301,-179.99796899482:-45.32195257858,179.99838806709

VLMMAP corrected position http://virtual-loup-de-mer.org/mercator.img.php?idraces=141505&lat=-45.297179474301&long=-179.99796899482&maparea=18&tracks=on&age=6&list=9361&x=1000&y=600&proj=mercator&text=right&seg2=-45.297179474301,-179.99796899482:-45.297179474301,-179.99796899482

```
Next Waypoint is 1, checking for WP crossing... 
    * WP   : -55.979000, -67.271000 <---> -64.000000, -60.000000
    * BOAT : -45.297179, -179.997969 <---> -45.297179, -179.997969:  *** NO ***
    *** NWP=1, DNM=3660.591843 
    *** ranking updated.
** Pilotmode=2/0, Angle updated, Heading = 67.704438755637
** DONE ** 
```

**Comment by Phille** [comment]
!!! y en a qui s'échouent aussi en passant AM  d'Ouest en Est !!!

(227) Checking user 6446: (race 141505) 
     Prev Hdg: 160 PIM=1/Heading=160
    Position update (WSpd=14.8, WHdg=21, Hours=0.0836, ANG=138.74, Hdg=160, BS=16.857, Dist=1.4094458997783nm) ... done
    Checking for coast crossing (vlm-c)
    Using: /home/vlm/vlmdatas/gshhs/gshhs_f.b

 Test basic segments intersections
1 0=0
2 1=1
3 R=-1
4 R=-1
6 R=-1
    **\* Processing exclusion zones (DB Loaded exclusion zone 141505)***
 179999.30162895 -46905.895544194 -179988.93609714 -46927.969642718 -150 -56 -130 -54
 179999.30162895 -46905.895544194 -179988.93609714 -46927.969642718 -130 -54 -125 -53
 179999.30162895 -46905.895544194 -179988.93609714 -46927.969642718 -125 -53 -120 -51
 179999.30162895 -46905.895544194 -179988.93609714 -46927.969642718 -120 -51 -115 -51
 179999.30162895 -46905.895544194 -179988.93609714 -46927.969642718 -115 -51 -110 -53
 179999.30162895 -46905.895544194 -179988.93609714 -46927.969642718 -110 -53 -105 -54.5
 179999.30162895 -46905.895544194 -179988.93609714 -46927.969642718 -105 -54.5 -100 -57.25
 179999.30162895 -46905.895544194 -179988.93609714 -46927.969642718 -100 -57.25 -75 -60
 179999.30162895 -46905.895544194 -179988.93609714 -46927.969642718 -75 -60 -70 -59
 179999.30162895 -46905.895544194 -179988.93609714 -46927.969642718 -70 -59 -65 -57.75
 179999.30162895 -46905.895544194 -179988.93609714 -46927.969642718 -65 -57.75 -60 -56.5
 179999.30162895 -46905.895544194 -179988.93609714 -46927.969642718 -60 -56.5 -55 -55
 179999.30162895 -46905.895544194 -179988.93609714 -46927.969642718 -55 -55 -50 -53.25
 179999.30162895 -46905.895544194 -179988.93609714 -46927.969642718 -50 -53.25 -45 -51
 179999.30162895 -46905.895544194 -179988.93609714 -46927.969642718 -45 -51 -40 -48
 179999.30162895 -46905.895544194 -179988.93609714 -46927.969642718 -40 -48 -35 -45 Intersection ratio 0.60603661589802

Intersection -179.99357204882 -46.919273621137
    **\* YES player 6446 CROSSED (vlmc), 
        Exclusion Zone has been crossed : 
            BOAT : -46.905896,179.999302 <----> -46.927970,-179.988936
            EncounterCoordinates -46.919273621137, -179.99357204882

GoogleMap http://maps.google.fr/maps?f=q&hl=fr&geocode=&q=-46.919273621137,-179.99357204882&ie=UTF8&spn=0.0191,0.082998&t=p&z=11&iwloc=addr. 

VLMMAP http://virtual-loup-de-mer.org/mercator.img.php?idraces=141505&lat=-46.905895544194&long=179.99930162895&maparea=18&tracks=on&age=6&list=6446&x=1000&y=600&proj=mercator&text=right&seg1=-46.919273621137,-179.99357204882:-46.919273621137,-179.99357204882&seg2=-46.905895544194,179.99930162895:-46.927969642718,-179.98893609714

VLMMAP corrected position http://virtual-loup-de-mer.org/mercator.img.php?idraces=141505&lat=-46.905895544194&long=179.99930162895&maparea=18&tracks=on&age=6&list=6446&x=1000&y=600&proj=mercator&text=right&seg2=-46.905895544194,179.99930162895:-46.905895544194,179.99930162895

```
Next Waypoint is 1, checking for WP crossing... 
    * WP   : -55.979000, -67.271000 <---> -64.000000, -60.000000
    * BOAT : -46.905896, 179.999302 <---> -46.905896, 179.999302:    *** NO ***
    *** NWP=1, DNM=3573.829432 
    *** ranking updated.
** Pilotmode=2/0, Angle updated, Heading = 21.256899507714
** DONE ** 
```

**Comment by Phille** [comment]
sbs, crois-tu pouvoir trouver une soluce?
j'ai fait passer qq bateaux manuelement ...

**Comment by sbsrouteur** [comment]
oui j'ai un patch qui fonctionne mais j'hésite à mettre en direct sur n2....

**Comment by maitaivw** [comment]
Hmm le NSZ n'est plus closed vue de qtvlm...

**Comment by Phille** [comment]
j'ai dû ajouter 2 segments ... et je les avais ajouté derrière les autres ... qtVlm ne marche pas bien avec ça ... j'ai dû changer tous les N° pour les mettre dans l'ordre et alors qtVlm a fermé la zone

**Comment by sbsrouteur** [comment]
Le fix évite le crash actuel sur la ligne d'antéméridien, mais ne va pas pour un passage de NSZ lors du passage de l'AM (style ligne des 60°S), donc à fixer calmement à tête reposée pour la prochaine release.
