### ISSUE TITLE
NSZ only visible on VLM maps with zoom between 2 & 4

### ISSUE THREAD

**Issue by Phille** [v-l-m/vlm#813]
Ya un pb sur les cartes VLM concernant les NSZ ... la NSZ n'est visible qu'avec un zoom inférieur ou égale à 4

**Comment by sbsrouteur** [comment]
Comment on centre la carte VLM autrement sur sur soi ou son WP pour voir la NSZ avec un zoom plus serré. depuis chez moi en zoom 5 je vois pas plus loin que 151W, donc la NSZ est pas encore à l'écran....

**Comment by Phille** [comment]
nan nan ... je "joue" avec la position de mon bateau dans l'URL de la carte et je centre la carte sur l'extremité NW de la NSZ ... et la NSZ est visible avec un zoom superieur à 4 

avec zoom 4

![nsz-zoom-4-01](https://cloud.githubusercontent.com/assets/11163172/6765359/e8ea1f0c-cfdc-11e4-8755-509bafcba1d9.JPG)

avec zoom 5

![nsz-zoom-5-01](https://cloud.githubusercontent.com/assets/11163172/6765372/88f68ff8-cfdd-11e4-95ad-f6b8cbc91101.JPG)

**Comment by sbsrouteur** [comment]
@pzia Comment on clear le cache de tiles dans cette zone du pacifique....

**Comment by pzia** [comment]
Je ne vois pas le lien entre les tiles et les nsz...

**Comment by sbsrouteur** [comment]
Y pas de cache pour la map vlm ?

**Comment by pzia** [comment]
Non. Il y a des tiles "legacy" dispo, mais les maps vlm redessinent à partir des gshhs qui sont montés en base (c'est d'ailleurs une part non négligeable de la charge de vlm).

**Comment by sbsrouteur** [comment]
bon ça fonctionne sur testing donc je vais vérifier si le code est à jour sur N2

**Comment by pzia** [comment]
C'est lié directement à la présence de l'ante-meridien sur la carte.
Si on a la longitude 180 de dessiné => OK
Si pas à l'écran => KO.
