### ISSUE TITLE
No Sailing Zone sur VLM Mobile

### ISSUE THREAD

**Issue by cavisk** [v-l-m/vlm#815]
Bonjour,
La NSL (No Sailing Zone) ne s'affiche pas sur VLM mobile.
Est il possible de l'afficher ? (quand vous aurez le temps) ;)
Merki

Hello
The NSL (No sailing Zone) does not appear.
Can you fix it? (ASAP)
Thanks

**Comment by pzia** [comment]
Vlm mobile utilise les mêmes cartes que le site en principe. 

@cavisk : tu as des screenshot comparatifs ?

**Comment by cavisk** [comment]
@pzia : Ci joint le Screenshot à zoom 2 sur ''VLM Mobile''
![mercator img 1](https://cloud.githubusercontent.com/assets/11610007/6782679/c273c6a8-d175-11e4-961e-87e2ab700353.PNG)
J'ai comparé avec le zoom 2 sur ''VLM officiel'', la NSZ apparaît.
La je viens de regarder en zoom 3 sur ''VLM Mobile''. Toujours pas de NSZ apparente.
Je pourrais transmettre plus de screenshot plus tard. Quand j'aurai une connexion wifi. ;)
La je suis au boulot et j'ai des accès restreins. 
Il faut aussi que je descende plus au sud pour voire à un zoom supérieur à 3.

**Comment by pzia** [comment]
C'est lié au #813  (même bug à mon avis). A suivre quand ce sera rêglé côté site.

**Comment by cavisk** [comment]
OK. On fait au feeling ou sur vlm officiel en attendant. ;-)
Quand je serai assez proche je regarderai à zoom 4 et plus.
Merci.

**Comment by sbsrouteur** [comment]
Réglé avec la correction de #813
