### ISSUE TITLE
En cas d'arrivée serrée, les notification sont en ordre inverse

### ISSUE THREAD

**Issue by sbsrouteur** [v-l-m/vlm#819]
Il doit manquer un tri dans la requête de récupération des news, du coup les messages qui sont envoyés dans le même batch sont postés en ordre chronologique inverses.

**Comment by pzia** [comment]
```
  $query .= "ORDER BY `timetarget` ASC ";
```

Pourtant ça a l'air bon

**Comment by pzia** [comment]
sur l'arrivée de la San Fernando, il n'y a que Facebook qui est en dispersé

**Comment by pzia** [comment]
On peut jouer sur le ratelimit (le mettre à 1 pour ne poster chaque minute qu'une seule news).
Ou bien tenter un sleep(10 secondes), au moins pour facebook et twitter mais bon...

**Comment by sbsrouteur** [comment]
C'est surtout dans le mail (gmail) que j'ai vu ça. twitter était dans
l'ordre ce matin. Mais s'il y a un ordre de tri explicite closons
