### ISSUE TITLE
Adresse mail

### ISSUE THREAD

**Issue by Phille** [v-l-m/vlm#820]
Est-ce que les adresses vlm-trac@googlegroups.com et vlm-devel@googlegroups.com sont encore actives?

**Comment by pzia** [comment]
Oui. 

Trac va être fermé car n'est plus utile avec github

**Comment by Phille** [comment]
THX.

**Comment by pzia** [comment]
J'ai supprimé le groupe vlm-trac.
On garde vlm-devel pour l'instant (mais passer à un truc sans google est tentant).
