### ISSUE TITLE
mod_deflate pour le cache

### ISSUE THREAD

**Issue by pzia** [v-l-m/vlm#824]
tout est dans le titre.
Pour le cache (et en particulier les gribs), on activerait le mod_deflate d'Apache qui compresserait les fichiers quand le client lui demanderait.

**Comment by maitaivw** [comment]
Ca pourrait etre fait pour la plupart (tous?) des ws non? Je pense en particulier a raceInfo et tracks. Je connais mal les implications cote serveur donc bon...

J'ai active ca par defaut dans qtVlm qd j'ai teste avec windgrid.php, et d'apres moi c'est le seul ws en ce moment qui supporte ca. Y'a p-tet (surement) une bonne raison qui m'echappe...

**Comment by pzia** [comment]
La compression consomme du cpu.
On a pas trop de sujet à ce niveau là.

Le plus intéressant c'est pour tout ce qui est mis en cache côté serveur.
Mais je ne pense pas que le serveur stocke la version compressée...

Pour rappel, le dispositif de cache global :
- serveur fabrique le résultat d'une requête
- si la requête est cachable, elle a un "maxage" > 0
- elle est mis en cache au niveau serveur pour la durée du maxage
  -> ça bénéficie aux autres clients qui demanderaient la même ressource
- elle est stockée côté client (ou pas, mais par défaut oui si c'est un
  navigateur)
- le navigateur réutilise (côté client) son cache pour la durée du maxage
  (si pas vidage de cache volontaire)
  -> ça bénéficie au client lui même
  -> ce serait une bonne pratique si les outils respectait cet entête

Tout est dans le périmètre du cache en principe.

En plus de tout ça, il y a un cache applicatif pour un certain nombre de
ressource
(les images de courses etc..., les tiles, etc...)
Un peu redondant maintenant, mais plus basique.

**Comment by pzia** [comment]
En fait, le mod deflate est censé être activé partout.

Y'a des trucs pas clean dans la gestion du cache serveur, ça peut expliquer
que le gzip ne se déclenche pas pour la plupart des ws.

je vais regarder...

**Comment by maitaivw** [comment]
Dans windgrid.php y'a ca

function send_json_header() {
        header("Content-type: application/json; charset=UTF-8");
    header("Content-Encoding: gzip");
        $cache = get_grib_validity();
        header("Cache-Control: max-age=".$cache.", must-revalidate");
    }
et a la fin y'a

echo gzencode(json_encode($windgrid));

A ma connaissance c'est le seul ws qui renvoie du gzip.

**Comment by pzia** [comment]
Oui, j'ai vu. Je peux le forcer comme ça mais je chercherai si ça ne peut
pas être négocié automatiquement
