### ISSUE TITLE
SSL et Xmpp

### ISSUE THREAD

**Issue by maitaivw** [v-l-m/vlm#828]
Est-il possible et souhaitable de permettre des connexions non-ssl pour le chat-vlm?

Comme on n'echange pas de coordonnees bancaire niveau securite c'est pas tres grave. Et vu du point de vue des outils ca oblige a fournir des lib SSL avec potentiellement des pbs de droits en particulier sous windows, a gerer 64bits/32bits, sans compter un peu de cpu en plus des 2 cotes....

C'est pas tres grave mais si on pouvait se passer de SSL de mon point de vue ca serait mieux.

**Comment by ylafon** [comment]
Un peu de lecture:
https://www.w3.org/2001/tag/doc/web-https
https://tools.ietf.org/html/rfc7258

**Comment by oxygen77** [comment]
Yes perso je pense aussi qu'il faut maintenir du ssl. 

Christophe

**Comment by maitaivw** [comment]
Oki oki, fallait tenter... ;)
