### ISSUE TITLE
NSZ latitude et longitude inversés sur la page instructions de course!

### ISSUE THREAD

**Issue by Phille** [v-l-m/vlm#831]
http://www.virtual-winds.org/forum/index.php/topic/7447-vlm-ocean-race-2014-2015/?p=265008

**Comment by Phille** [comment]
sbs, pourrais-tu corriger stp?
pour les WP c'est OK
pour les NSZ c'est NOK

![lat-long-switched](https://cloud.githubusercontent.com/assets/11163172/7573497/616032f2-f826-11e4-97f0-50112b76d27a.PNG)

**Comment by Phille** [comment]
est-ce déjà sur N2?

**Comment by sbsrouteur** [comment]
non ça ira sur N2 lors de la prochaine mise à jour. Je fini le patch du #834 puis je met ça sur testing pour que vous puissiez tester. Une fois OK pour tout le monde on avisera quand on peut faire une maj de N2.

(quoi que pour ce patch je peux faire la modif sauvagement sur N2, mais c'est toujours mieux de faire les choses bien)

**Comment by maitaivw** [comment]
Ca m'interesse de savoir qd la prochaine maj aura lieu et si elle contiendra le necessaire pour les gribs partiels ;)

**Comment by pzia** [comment]
On a parlé du 26 mai ou du 3 juin avec sbs...
