### ISSUE TITLE
VOR 9  pit-stop

### ISSUE THREAD

**Issue by Phille** [v-l-m/vlm#834]
Lors de la VOR9 y aura un pit-stop de 24h ... comment faire avec VLM ?
En réel les bateaux s'arrêteront pendant 24h à La Haye et repartiront dans le même ordre qu'arrivés (aussi même interval)

**Comment by Frogeater29** [comment]
si on fait un wp standard avec un gel du moteur 24h dès que le premier arrive, ca le ferait?

si on ouvre une 2eme course, tout le monde partira en meme temps.

prevoir un décalage personnalisé doit faire pas mal de dev.

Frog

**Comment by sbsrouteur** [comment]
Je pensais faire 2 courses avec un stop & go au démarrage de la seconde
ajusté pour chaque bateau en fonction de son arrivée sur la première. Ca
fait exactement la même chose que le pit-stop.

La seule question à tester est : "est ce que le stop & go" reste au départ
de la course.

++

2015-05-09 13:29 GMT+02:00 Frogeater notifications@github.com:

**Comment by Frogeater29** [comment]
ah oui! pas si con que ça! idée géniale, a creuser.
A+

**Comment by Phille** [comment]
2 courses!? Faire gaffe que personne ne s'inscrit pour la 2ème!

**Comment by Phille** [comment]
est-il possible de "freeze" le moteur pour un course et pas pour les autres?

**Comment by Phille** [comment]
Après une bonne nuit de reflection:
sbs tu m'avais dit qu'on pouvait mettre un S&G pour une NSZ qui est different des "coast crossing", tu confirmes?
Je crée un segment NSZ qui bloque le passage à la hauteur de La Haye. Ce segment aura un S&G de 24h ... et un peu moins de 24h après le bloquage du 1er bateau j'efface ce segment et les bateaux pourront continuer leur route sans pb. (chacun aura un S&G de 24h)

**Comment by sbsrouteur** [comment]
1/ pas de S&G particulier pour les NSZ actuellement
2/ Seuls les bateaux arrivés dans les premières 24h auront le pitstop. On
peut se demander ensuite l'utilité d'un tel pit stop s'il ne s'applique pas
à tous. (Genre j'arrive 23h59h après le premier et je repars 24h après
celui qui a passé la ligne  avec 24h01 de retard sur le premier).

3/ Alternative qui est direct disponible dans VLM: ajouter deux portes à
passer (la seconde est la même que celle du pit stop) qui ajoutent environ
24h à la course.

2015-05-10 9:31 GMT+02:00 Phille notifications@github.com:

**Comment by Phille** [comment]
pour les 24h pas de pb je crois ... Le départ est à Lorient ça fait +/- 520NM ... y aura pas 24h de dif entre le 1er et le dernier, non?

**Comment by sbsrouteur** [comment]
En fait maintenant que j'y pense on a (preque) tout ce qu'il faut dans le
moteur pour ajouter un S&G de 24 lors du franchissement du WP. Et y a pas
besoin de faire de seconde course ou quoi que ce soit.

**Comment by sbsrouteur** [comment]
j'essaye de vous mettre un proto sur testing ce soir.

2015-05-10 11:25 GMT+02:00 St. B. sbarthes@gmail.com:

> En fait maintenant que j'y pense on a (preque) tout ce qu'il faut dans le
> moteur pour ajouter un S&G de 24 lors du franchissement du WP. Et y a pas
> besoin de faire de seconde course ou quoi que ce soit.
>

**Comment by pzia** [comment]
@sbsrouteur : un nouveau type de Wp, le problème étant le paramètrage du
temps de stand by, non ?

**Comment by sbsrouteur** [comment]
@pzia : oui bien sur, le type de WP est la bonne solution, mais à quoi bon. On ne va s'en servir qu'une fois tous les 10 ans. Donc une petite verrue pour ce cas particulier me semble suffisante. Sauf bien sur si le comité de course voit un interêt à ce genre de fonction dans les WP.

Mais perso, sauf à vouloir respecter la réalité de la course, je ne suis pas convaincu que ça apporte quelquechose.

**Comment by Phille** [comment]
La seule et unique raison: vouloir respecter la réalité de la course. ;)

**Comment by pzia** [comment]
je disais juste ça parce que je vois pas trop la différence entre la verrue
et un nouveau type de porte.

**Comment by sbsrouteur** [comment]
Bon j'ai mis en place la verrue sur testing sur la course 150101 3 mers saint miquelon. Au passage du WP1 vous prendrez 24h de stop and go.

Je vous laisse faire quelques tests pour vérifier que :
- Ca ne fout pas la grouille dans les autres courses
- Que ça fonctionne bien sur le WP prévu

Y a quand même un effet de bord qui est que suite au pit stop, on se retrouve face au vent et il faut impérativement mettre un ordre pour que le bateau reparte. 
J'ai mis une trace qui j'enlèverrai pour le passage en prod qui dit "pit stop check" à chaque passage de WP indépendament de la course. Et il y a un message "Pit Stop at waypoint crossing" dans les actions utilsateur pour prévenir de la cause de l'arrêt.

**Comment by Phille** [comment]
bateau bloqué hier ... encore 219 minutes de S&G.
j'ai mis cap fixe pour m'en sortir on verra si ça marche comme prévu ;)

![pitstop](https://cloud.githubusercontent.com/assets/11163172/7648297/c50015d0-fae1-11e4-8e9a-63d191fea8be.PNG)

**Comment by Phille** [comment]
1° Passage du WP(à sens unique) est ok, on est bloqué pour 24h ... passage dans le mauvais sens: on est pas bloqué.
2° Passage de cette ligne (imaginaire) sur une autre course ne donne aucun pb. :)
