### ISSUE TITLE
Accès N2 & testing impossible

### ISSUE THREAD

**Issue by Phille** [v-l-m/vlm#836]
Je n'ai plus accès à VLM! :(

**Comment by sbsrouteur** [comment]
Peux-tu préciser quel accès ne fonctionne plus? :
- web
- console admin
- ftp
- ssh
- autre ?

++

**Comment by Phille** [comment]
accès web! (N2 et testing)
je n'ai rien essayé d'autre ...

**Comment by sbsrouteur** [comment]
tu te logges philles@virtual-winds.org ?

**Comment by Phille** [comment]
N2: phille@virtual-winds.org
Testing: phille.x5@gmail.com

**Comment by pzia** [comment]
Il te dit quoi ?
Tu as essayé de réinitialiser le mot de passe ?

**Comment by Phille** [comment]
j'avais pas le temps de faire des essais ... mais message simple: pas accès à ce website (vérifier l'adresse, etc....)

**Comment by Phille** [comment]
je n'étais pas le seul à voir les messages sur le comptoir!

**Comment by Phille** [comment]
voici les messages:

![pb-vlm-01](https://cloud.githubusercontent.com/assets/11163172/7665181/59aa1b66-fbac-11e4-8f00-d52632674bb6.PNG)

**Comment by pzia** [comment]
Ça ressemble à un pb de routage ou de Dns

**Comment by sbsrouteur** [comment]
J'ai cherché dans les logs, mais je ne trouve rien de particulier.

DNS c'est zarb car N2 ne change normalement pas d'IP. Ptet un Pb de routage effectivement. Ce qui est le combe pour un site comme vlm :p
