### ISSUE TITLE
pb maj MTO

### ISSUE THREAD

**Issue by Frogeater29** [v-l-m/vlm#837]
le script saute fréquemment 3h, Ca arrive lors de la conversion du zip en grb, si pb, on continue comme si de rien n'etait. hier soir c'etait plus visible, car c'est le 12h qui a sauté, donc pas de maj.
il faut boucler au delà du wget, sur l"ensemble du process de traitement des bouts de 3h

Extrait du log
--2015-05-26 21:34:53--  http://nomads.ncep.noaa.gov/cgi-bin/filter_gfs_0p50.pl?file=gfs.t18z.pgrb2full.0p50.f012&lev_10_m_above_ground=on&var_UGRD=on&var_VGRD=on&leftlon=0&rightlon=360&toplat=90&bottomlat=-90&dir=%2Fgfs.2015052618
Resolving nomads.ncep.noaa.gov (nomads.ncep.noaa.gov)... 140.90.101.62
Connecting to nomads.ncep.noaa.gov (nomads.ncep.noaa.gov)|140.90.101.62|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [application/octet-stream]
Saving to: `gfs.t18z.pgrb2full.0p50.f012'

```
 0K .......... .......... .......... .......... .......... 4.34K
50K .......... .......... .......... .......... .......... 3.22K
```

   100K .......... .......... .......... .......... .......... 13.2K
   150K .......... .......... .......... .......... .......... 9.72K
   200K .......... .......... .......... .......... .......... 17.5K
   250K .......... .......... .......... .......... .......... 32.7K
   300K .......... .......... .......... .......... .......... 41.7K
   350K .......... .......... .......... .......... .......... 12.6K
   400K .......... .......... .......... .......... .......... 19.7K
   450K .......... .......... .......... .......... .......... 7.21K
   500K .......                                                33.9K=55s

2015-05-26 21:35:56 (9.19 KB/s) - `gfs.t18z.pgrb2full.0p50.f012' saved [519685]

wget returned 0
20150526 gfs.t18z.pgrb2full.0p50.f012 downloaded...
gfs.t18z.pgrb2full.0p50.f012 converted
Invalid GRIB entry
Error reading GRIB file, found odd number or records
--2015-05-26 21:35:56--  http://nomads.ncep.noaa.gov/cgi-bin/filter_gfs_0p50.pl?file=gfs.t18z.pgrb2full.0p50.f015&lev_10_m_above_ground=on&var_UGRD=on&var_VGRD=on&leftlon=0&rightlon=360&toplat=90&bottomlat=-90&dir=%2Fgfs.2015052618
Resolving nomads.ncep.noaa.gov (nomads.ncep.noaa.gov)... 140.90.101.62
Connecting to nomads.ncep.noaa.gov (nomads.ncep.noaa.gov)|140.90.101.62|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [application/octet-stream]
Saving to: `gfs.t18z.pgrb2full.0p50.f015'

```
 0K .......... .......... .......... .......... .......... 8.09K
50K .......... .......... .......... .......... .......... 4.09K
```

   100K .......... .......... .......... .......... .......... 6.29K
   150K .......... .......... .......... .......... .......... 26.8K
   200K .......... .......... .......... .......... .......... 48.1K
   250K .......... .......... .......... .......... .......... 19.8K
   300K .......... .......... .......... .......... .......... 4.21K
   350K .......... .......... .......... .......... .......... 7.17K
   400K .......... .......... .......... .......... .......... 4.83K
   450K .......... .......... .......... .......... .......... 33.5K
   500K .........                                              46.5K=63s

2015-05-26 21:37:00 (8.13 KB/s) - `gfs.t18z.pgrb2full.0p50.f015' saved [521985]

**Comment by Frogeater29** [comment]
complement:
le 30 et le 33 n'ont pas la bonne taille, mais le script convertit tout ca, sans erreur et ajoute ca au .grb

--2015-05-26 21:45:52--  http://nomads.ncep.noaa.gov/cgi-bin/filter_gfs_0p50.pl?file=gfs.t18z.pgrb2full.0p50.f030&lev_10_m_above_ground=on&var_UGRD=on&var_VGRD=on&leftlon=0&rightlon=360&toplat=90&bottomlat=-90&dir=%2Fgfs.2015052618
Resolving nomads.ncep.noaa.gov (nomads.ncep.noaa.gov)... 140.90.101.62
Connecting to nomads.ncep.noaa.gov (nomads.ncep.noaa.gov)|140.90.101.62|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [application/octet-stream]
Saving to: `gfs.t18z.pgrb2full.0p50.f030'

```
 0K .......... .......... .......... .......... .......... 38.6K
50K .......... .......... .......... .......... .......... 43.8K
```

   100K .......... .......... .......... .......... .......... 44.6K
   150K .......... .......... .......... .......... .......... 7.08K
   200K .......... .......... .......... .......... .......... 19.6K
   250K .......... .......... .......... .......... .......... 35.6K
   300K .......... .......... .......... .......... .......... 51.5K
   350K .......... .......... .......... .......... .......... 16.4K
   400K .......... .......... .......... ........               146 =4m49s

2015-05-26 21:50:42 (1.52 KB/s) - `gfs.t18z.pgrb2full.0p50.f030' saved [449104]

wget returned 0
20150526 gfs.t18z.pgrb2full.0p50.f030 downloaded...
gfs.t18z.pgrb2full.0p50.f030 converted
--2015-05-26 21:50:42--  http://nomads.ncep.noaa.gov/cgi-bin/filter_gfs_0p50.pl?file=gfs.t18z.pgrb2full.0p50.f033&lev_10_m_above_ground=on&var_UGRD=on&var_VGRD=on&leftlon=0&rightlon=360&toplat=90&bottomlat=-90&dir=%2Fgfs.2015052618
Resolving nomads.ncep.noaa.gov (nomads.ncep.noaa.gov)... 140.90.101.62
Connecting to nomads.ncep.noaa.gov (nomads.ncep.noaa.gov)|140.90.101.62|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [application/octet-stream]
Saving to: `gfs.t18z.pgrb2full.0p50.f033'

```
 0K .......... .......... .......... .......... .......... 45.1K
50K .......... .......... .......... .......... .......... 3.33K
```

   100K .......... .......... .......... .......... .......... 15.2K
   150K .......... .......... .......... .......... .......... 4.50K
   200K .......... .......... .......... .......... .......... 12.4K
   250K .......... .......... .......... .......... .......... 11.2K
   300K .......... .......... .......... .......... .......... 10.0K
   350K .......                                                29.4K=44s

2015-05-26 21:51:28 (8.09 KB/s) - `gfs.t18z.pgrb2full.0p50.f033' saved [366417]

wget returned 0
20150526 gfs.t18z.pgrb2full.0p50.f033 downloaded...
gfs.t18z.pgrb2full.0p50.f033 converted

**Comment by sbsrouteur** [comment]
Le script actuel est très limité. Il se contente de prendre les fichiers et de vérifier qu'il ont une taille minimale. En cas de fichier incomplet ou corrompu, il n'y a aucun contrôle.

Comment fait-tu pour dire "le fichier 30 est incomplet" ?

As-tu gardé un de ces fichiers incomplets ? 

PS : La NOAA a changé du matos pour le serveurs meteo, et ils continuent d'avoir des problèmes avec leur nouveau matos. C'est ptet lié....

**Comment by RisAMer** [comment]
Bon, ben ça push pas.

@sbs: Essaye d'ajouter ça après le test de size (L98 noaa.sh):

```
 #uncommenting next line should trigger the test for record number
  #wgrib2 $GRIBFILE -for 1:1 -grib $GRIBFILE
  #checks Number of records
  recordsNumber=$((wgrib2 "$GRIBFILE" -count 1>/dev/null) 2>&1 |grep -o '[0-9]\+')
  if [ "$recordNumber" -ne 2]
 echo "Grib File has $recordNumber record(s)... Retrying" >>$LOG
 rm -f $GRIBFILE
     let retry=1
  fi
```

Hier soir, le test de windserver sauve la mise mais c'est pitêtre pas plus mal de le mettre au niveau du DL. Pas testé.
Pas sûr que wgrib2 soit installé, remarque. ;)

**Comment by Frogeater29** [comment]
les fichiers 30 et 33 etaient corrompus, car apres dezip ils ne faisaient pas 826K, mais seulement 450k.
De mémoire, en .GRB la taille est toujours la même.

**Comment by RisAMer** [comment]
L'interim de la 18z (j'ai tjs le fichier si tu veux):
1:0:d=15052618:UGRD:kpds5=33:kpds6=105:kpds7=10:TR=10:P1=0:P2=0:TimeU=1:10 m above gnd:anl:NAve=0
2:422454:d=15052618:VGRD:kpds5=34:kpds6=105:kpds7=10:TR=10:P1=0:P2=0:TimeU=1:10 m above gnd:anl:NAve=0
3:844908:d=15052618:UGRD:kpds5=33:kpds6=105:kpds7=10:TR=10:P1=0:P2=3:TimeU=1:10 m above gnd:3hr fcst:NAve=0
4:1267362:d=15052618:UGRD:kpds5=33:kpds6=105:kpds7=10:TR=10:P1=0:P2=6:TimeU=1:10 m above gnd:6hr fcst:NAve=0
5:1689816:d=15052618:VGRD:kpds5=34:kpds6=105:kpds7=10:TR=10:P1=0:P2=6:TimeU=1:10 m above gnd:6hr fcst:NAve=0
6:2079780:d=15052618:UGRD:kpds5=33:kpds6=105:kpds7=10:TR=10:P1=0:P2=9:TimeU=1:10 m above gnd:9hr fcst:NAve=0
7:2502234:d=15052618:VGRD:kpds5=34:kpds6=105:kpds7=10:TR=10:P1=0:P2=9:TimeU=1:10 m above gnd:9hr fcst:NAve=0
8:2892198:d=15052618:UGRD:kpds5=33:kpds6=105:kpds7=10:TR=10:P1=0:P2=12:TimeU=1:10 m above gnd:12hr fcst:NAve=0
9:3314652:d=15052618:VGRD:kpds5=34:kpds6=105:kpds7=10:TR=10:P1=0:P2=12:TimeU=1:10 m above gnd:12hr fcst:NAve=0

Record 3hr: U s'ennuie tout seul, sans son V.

Avec l'effet de la compression, pas forcément commode de trouver le bon seuil si on veut tester avant la conversion en grib1. Mais 300000, apparemment, ça suffit pas. ;)
C'est vrai, les serveurs de la NOAA ramaient +++ au moment de la MAJ.

**Comment by sbsrouteur** [comment]
@Frogeater29 J'ai fait la mise à jour simple qui consiste à vérifier la taille du fichier grib1. Chez moi ce week-end 844908. Mais ce matin sur testing c'est 812418.

Je rollback cette modif ou il y a une astuce?

D'ailleurs je viens de regarder chez moi, ça fait aussi  812418 ce matin. Donc on doit pouvoir dire que le grib1 n'a pas une taille constante dans le temps....

**Comment by sbsrouteur** [comment]
Bon je viens de relancer à la main la maj sur testing et les fichiers sont à nouveau à 844908. Est-ce que la taille du fichier dépend de l'heure de la MAJ ?

**Comment by RisAMer** [comment]
Aucune idée, mais j'ai peur qu'un test d'égalité ne génère trop de faux-positifs. Si tu souhaites te restreindre à un test de taille, ce que j'aurais tendance à faire, c'est une statistique sur la taille des U, une statistique sur la taille des V, moyenne de taille pour un record; fixer le seuil à 1.5x la moyenne et tester qu'on n'est pas en-dessous.

D'autre part, tant que tu as le nez dedans, il me paraîtrait souhaitable que le grib n'apparaisse dans http://grib.virtual-loup-de-mer.org/ qu'après qu'il a été validé par le windserver. Ça crée une confusion inutile pour la très grande majorité des gens.

**Comment by sbsrouteur** [comment]
"D'autre part, tant que tu as le nez dedans, il me paraîtrait souhaitable que le grib n'apparaisse dans http://grib.virtual-loup-de-mer.org/ qu'après qu'il a été validé par le windserver. Ça crée une confusion inutile pour la très grande majorité des gens."

Cette phrase crée une confusion pour moi. Peux tu préciser ce à quoi tu penses?

**Comment by RisAMer** [comment]
Ce qu'on a constaté lors du problème de MAJ le 26/05:
Le grib arrive incomplet. Il s'affiche sur l'Url des gribs. On voit un interim, on se dit que la MAJ s'est faite. Que nenni.  Il est envoyé au windserver, qui énumère ses petits, dit non y'a quelquechose qui cloche, j'ai pas le compte, et refuse le colis. Pour voir l'état de la mise à jour, faut aller vérifier les windtables.

En inversant l'ordre des opérations ici:
    cat $GRIBFILE.grib1 >> ${PREFIX}-${DAT}${HH}.grb
    if [ $TSTAMP -gt $TIME_THRESHOLD ]; then
      if [ ! -f $GRIBPATH/$INTERIM_NAME ]; then
        cp ${PREFIX}-${DAT}${HH}.grb $GRIBPATH/$INTERIM_NAME
      fi
      # we change the weather now
      if [ $updated -eq 0 ]; then
        windserver $PREFIX-${DAT}${HH}.grb >> $LOG 2>&1
        updated=1
      fi
    fi

Il doit être faisable de vérifier le code d'erreur que renvoie le windserver. Si OK, on envoie l'interim dans gribs.v-l-m.org. Si pas OK, on l'envoie pas, y'a pas d'interim, tout le monde comprend que la MAJ s'est pas faite. C'est pas grave, on a 120h en réserve de la MAJ précédente et on peut tenir un moment, on attend la suivante.

En plus, on peut s'appuyer sur les "sanity checks" intégrés au windserver, et on peut se permettre d'être un peu moins vigiilant dans les tests du script.

**Comment by Frogeater29** [comment]
SBS, on va etre trop court pour valider ça, il  faut enlever la modif pour le depart de la vor9, on fera avec.
c'est mon avis.
pour la résolution, je pense qu'il faut juste lancer un test d'intégrité apres chaque telech de 3h avec le serveur noaa, la taille semblant bouger de quelques octets (sans doute l'entete) la solution précédente n'est pas viable.

**Comment by sbsrouteur** [comment]
Ok je rollback cette modif pour ce soir. on verra pour le test avec wgrib2 pour la prochaine, mais c'est un outil supplémentaire à installer, c'est pour ça que j'avais pas creusé l'idée
