### ISSUE TITLE
Notification aux outils des changements de parcours

### ISSUE THREAD

**Issue by maitaivw** [v-l-m/vlm#838]
Hello,
Ca serait bien d'inclure la date de dernière mise à jour de la course dans le ws boatInfo (pour éviter d'avoir a appeler un autre ws). Avec juste cette info on peut prévenir le user que le parcours a changé et reloader tout le bazar automatiquement sans relancer... 

Non je dis pas ca pke j'avais oublié de relancer qtVlm sur la solo.. ;)

**Comment by sbsrouteur** [comment]
Il me semble qu'il y a un truc dans le genre dans raceinfo, car mon routeur cache les fichiers de def de courses en local, mais les recharge quand il faut. Je regarderai comment je procède.

**Comment by maitaivw** [comment]
Ok merci,
qtvlm n'appelle raceinfo que 1 seul fois au demarrage, et c'est donc pour savoir qd le rappeler que je voudrais cette info dans boatinfo, qui est le seul ws systematiquement appelé sur une sync.

**Comment by Frogeater29** [comment]
idem, je ne recharge qu'en changeant de bateau, c'est boatinfo que j'utilise uniquement lors de l'appui sur "actualiser". il faut ajouter une date de maj. (ca va rester génant quand meme, car le cache va garder l'info 1h dans raceinfo), donc la mise a jour ne sera pas effective reellement. il faut qu'elle soit datée à H+duree de cache ou un truc du genre

**Comment by maitaivw** [comment]
Ici y'a pas ce problème de cache que nous forçons à 0 de toutes façons. 

Du coup juste la date et heure de la derniere maj de la course suffirait
a mon bonheur.... 

Le 16-06-2015 14:47, Frogeater a écrit : 

> idem, je ne recharge qu'en changeant de bateau, c'est boatinfo que j'utilise uniquement lors de l'appui sur "actualiser". il faut ajouter une date de maj. (ca va rester génant quand meme, car le cache va garder l'info 1h dans raceinfo), donc la mise a jour ne sera pas effective reellement. il faut qu'elle soit datée à H+duree de cache ou un truc du genre 
> 
> ## 
> 
> Reply to this email directly or view it on GitHub [1].

## Links:

[1] https://github.com/v-l-m/vlm/issues/838#issuecomment-112413608

**Comment by sbsrouteur** [comment]
Bonjour,

j'ai cogité sur ce sujet pendant mes congés et j'en suis arrivé à l'idée suivante.

On ajoute dans la raceinfo une colonne index.
On ajoute dans la BD un trigger qui incrémente la valeur de l'index à chaque mise à jour d'une donnée qui concerne la race info (enreg dans raceinfo, wp, nsz, et les autres que j'oublie)
On modifie le WS boatinfo pour renvoyer l'index en cours de la raceinfo 
Les outils se démerdent pour se souvenir de l'index qu'ils ont lu pour faire les demandes lors de mise à jour. FT en particulier peut mettre à jour ses requêtes en ajouter un param &Q=<numindex> et ainsi contourner les contraintes de cache interne que renvoie pas les requêtes au serveur quand la demande ne change pas.

Si ça vous convient et que ça ne choque personne on peut mettre ça en musique sur testing d'ici à fin aout.
