### ISSUE TITLE
Gestion du cache pour les gribs tiles

### ISSUE THREAD

**Issue by sbsrouteur** [v-l-m/vlm#840]
@maitaivw  a dit :

Bon alors... c'est en prod, ca fonctionne nickel, c'est une révolution (vraiment)

Un détail me tarabuste néanmoins...

J'avais compris que si le tile etait deja généré, pas de redirection vers gribtiles.php, or j'ai systématiquement une redirection, meme si je demande 2 fois le meme tile unique.

Est-ce bien normal?

Ca donne ca dans ma console, systematiquement:

uncompressing network reply
redirected to "/gribtiles.php?south=45&west=-15&step=15&date=2015062312"
received "45/-15/2015062312.15.grb"

@pzia : est ce que la mise en cache est bien configurée pour ça?

**Comment by maitaivw** [comment]
Arf... Désolé pour le dérangement: Le bug est chez nous

J'ai oublié de retirer une url hardcodée avec testing, et du coup c'est ca qui force la redirection. Ca fonctionne mais les tiles sont regénérés à chaque fois. Je corrige et on re-livre ce soir.

My bad, c'est ma tournée, du coup.

**Comment by maitaivw** [comment]
@sbsrouteur tu peux fermer le ticket stp?
