### ISSUE TITLE
Webservice raceinfo

### ISSUE THREAD

**Issue by jeberger** [v-l-m/vlm#841]
J'ai un truc bizarre avec les webservices : cette adresse ne fonctionne pas (elle retourne simplement « 0 ») :
http://virtual-loup-de-mer.org/ws/raceinfo.php?idrace=20150703

Pourtant, cette adresse fonctionne (identique à la précédente, sauf un « / » doublé) :
http://virtual-loup-de-mer.org/ws//raceinfo.php?idrace=20150703

Et celle-ci fonctionne aussi (identique à la première mais pour une autre course) :
http://virtual-loup-de-mer.org/ws/raceinfo.php?idrace=20150619

Ce comportement se produit aussi bien avec le script qui établit les classements LMNH sur le serveur de virtual-winds et sur mon PC ainsi qu'avec Firefox sur mon PC…

**Comment by jeberger** [comment]
Suite à une remarque de Phille, testé avec `v-l-m.org` et ça marche

**Comment by pzia** [comment]
Faudra regarder, mais en passant, l'url officielle est :
http://virtual-loup-de-mer.org/ws/raceinfo/desc.php?idrace=20150703

Celles qui sont à la racine de /ws/ n'ont été gardées que pour des raisons
de compatibilité
