### ISSUE TITLE
Gestion des polaires

### ISSUE THREAD

**Issue by sbsrouteur** [v-l-m/vlm#842]
Pourquoi est ce que l'on a deux dossiers de polaires ? un pour le chargement en mémoire des polaires et un dans site pour afficher les polaires de bateaux.

un seul dossier ne serait pas plus simple?

**Comment by pzia** [comment]
Historiquement, Vlm a été conçu pour que le moteur puisse tourner sur un
serveur maître indépendant des frontaux Web.

Voilà pour l'explication :-)
