### ISSUE TITLE
Position bateau sur VLM100 après changement de coordonnées n'est pas mis à jour!

### ISSUE THREAD

**Issue by Phille** [v-l-m/vlm#843]
Position bateau sur VLM 100 après changement de coordonnées du point de départ n'est PAS repris sur VLM100 et les outils n'ont pas le bon point de départ sur leurs cartes :( (prennent p-tet les infos au mauvais endroit !?)
Sur la carte VLM c'est OK.
Voir les photos: http://www.virtual-winds.org/forum/index.php/topic/7516-tour-de-france-2015/?p=266086

**Comment by sbsrouteur** [comment]
Les positions des bateaux sont mise à jour par le moteur. Donc lorsque la course n'est pas ouverte, les positions ne bougent pas.

Le boat prend une position lors de son inscription et elle n'est plus mise à jour avant la première vac. Il manque un trigger pour remettre au point de départ tous les bateaux inscrits, en cas de modification.

**Comment by Phille** [comment]
... mais la mod est bien prise en compte sur la carte VLM !? Quid?
Est-ce difficile (beaucoup de boulot) d'ajouter un "trigger"?

**Comment by sbsrouteur** [comment]
Je pense (sans regarder dans le code), que VLM place les points sur la carte avant le début de la course, sans demander où les bateaux sont réellement.

la mise en place du trigger n'est pas un boulot énorme, mais je ne pourrai pas m'y intéresser avant le mois d'aout. Le ticket est affecté pour la prochaine version, car c'est effectivement un bon manque fonctionnel.

**Comment by Phille** [comment]
Merci.

Ya pas le feu au lac J
