### ISSUE TITLE
Plus de place sur /Home

### ISSUE THREAD

**Issue by sbsrouteur** [v-l-m/vlm#845]
Plus de place sur le volume. A priori, grossissement du cache gribtiles, et absence de nettoyage.

Mettre en place un cron de nettoyage du dossier pour limiter la croissance d'espace disque.

**Comment by sbsrouteur** [comment]
Commande d'extend de LV :
lvextend -L+1G -r /dev/mapper/vg00-lv_home

**Comment by Phille** [comment]
je crois que François a ajouté de la place sur notre DD ...

**Comment by sbsrouteur** [comment]
Y a eu extension de 1G par Paparazzia, puis un peu de ménage. Il est
possible que FM a ajouter un peu plus après. J'ai pas recontrôlé depuis.

2015-09-27 23:05 GMT+02:00 Phille notifications@github.com:

**Comment by Phille** [comment]
je ne savais pas que papa était intervenu ... merci papa ;)
