### ISSUE TITLE
Mails de VLM considérés comme SPAM

### ISSUE THREAD

**Issue by Phille** [v-l-m/vlm#846]
François nous demande plus d'info pour pouvour peaufiner les mails en provenance de VLM:
Pas eu le temps de peaufiner pour les mails, mais ça m'aiderait si
quelqu'un me disait / rappelait quels sont les cas où VLM envoit un
mail, quel action dans le jeu engendre un mail, quel partie du code,
quelle est l'adresse émettrice, etc... afin que je gagne du temps en
recherchant.

J'ai connaissance de 2 mails: 1 pour confirmation d'inscription et 2 Coast Crossing

**Comment by sbsrouteur** [comment]
Je ne crois pas avoir vu d'autres cas, que les deux que tu cites. Perso, je n'ai jamais reçu aucun email de coast crossing que ce soit sur testing ou en prod.

**Comment by Phille** [comment]
Coast Crossing est envoyé à:
-F@v-l-m.org
VLM-ENGINE@v-l-m.org
vlm@virtual-winds.org

**Comment by sbsrouteur** [comment]
on peut clore ou il y a quelque chose à faire?
