### ISSUE TITLE
Annulation de changement lors du transfert testing>neptune2

### ISSUE THREAD

**Issue by Phille** [v-l-m/vlm#847]
Je change qq coordonnées de WP d'une course sur testing et lors du transfert vers neptune2 les changements ne sont pas pris en compte alors que sur testing c'était ok.
Quid?

**Comment by Phille** [comment]
Pas uniquement les changements sont ignorés mais même l'écrasement (via putty) de la course entière est ignoré!?

**Comment by sbsrouteur** [comment]
je ne t'ai pas oublié pour ce point là, mais pas eu trop de le temps.
J'essai de regarder ça ce week-end (i.e. demain)

2015-11-21 13:02 GMT+01:00 Phille notifications@github.com:
