### ISSUE TITLE
WiKi VLM

### ISSUE THREAD

**Issue by Phille** [v-l-m/vlm#849]
Le wiki VLM est HS ... bloqué à la page "acceuil"

**Comment by sbsrouteur** [comment]
@pzia   Est-ce-que ce n'est pas que l'URL dans le fichier de config pointe encore vers VLM alors qu'elle devrait aller vers github??

Si oui je peux patcher l'url dans config.php, ainsi que celle dans neptune.

**Comment by Phille** [comment]
je ne crois pas que github soit impliqué ... ya aussi un pb avec la bouée SOS qui n'envoit plus de mail ... c'est un pb VLM je crois.
Le wiki fonctionnait encore ya qq semaines

Message d'un joueur:
Salut

Le wiki n'est plus accessible, il revient tjs sur l'accueil.

gilles (gil49100)

Ps le SOS sur vlm ne marche plus non plus..

**Comment by pzia** [comment]
pour @fmicaux c'est un pb sur la machine virtuelle qui porte le wiki
- le ftp fonctionne correctement (je vois bien le code mediawiki et ses
  paramétrages)
- la base de données locale est probablement innacessible

**Comment by pzia** [comment]
pour le SOS : il marche bien, mais il dépends du bon paramétrage du client mail du PC.

**Comment by Phille** [comment]
Yep t'as raison ... le SOS marche, j'ai inscrit un bateau et lancé un SOS >>> c'est OK
Merci ;)

**Comment by sbsrouteur** [comment]
La base données du wiki fonctionne, c'est un pb d'affichage

Si on passe en mode édition le code de la page est bien présent. Si tu
demande une page au hasard ça fait pareil, mais la page et son source sont
accessibles.

En cherchant wikimedia empty content on trouve des trucs sur un problème de
maj. Ptet qu'on pourrait commencer par mettre à jour le wiki?

2016-01-09 9:44 GMT+01:00 paparazzia notifications@github.com:

> pour @fmicaux c'est un pb sur la machine virtuelle qui porte le wiki
> - le ftp fonctionne correctement (je vois bien le code mediawiki et ses
>   paramétrages)
> - la base de données locale est probablement innacessible
>

**Comment by fmicaux** [comment]
Salut tous,

J'ai fait pas mal de travaux et montées de version sur le serveur 
"web01.actilis.net"

Il accepte maintenant :
- PHP4.4.9, historique, via CGI (ce matin pas mal d'interruptions et 
  redémarrages de l'httpd-2.4 pour intégrer ça)
- PHP 5.4, 5.5, 5.6, 7.0, via fastCGI / PHP-FPM.

S'il y a un paramétrage particulier pour le wiki, je le mettrai en place.

Si tout est résolu à l'heure qu'il est et pour l'heure du midi au moins, 
c'est que le problème était lié à mes interruptions de services de ce 
matin, non prévues certes. Non, je n'ai pas testé en prod, j'ai juste 
pas mal remanié de confs et fait quelques ajustements "à chaud".

François

**Comment by fmicaux** [comment]
à toutes fins utiles, la déclaration du vhost concernant le wiki :

<VirtualHost *:80>
         ServerAdmin admin@wiki.virtual-loup-de-mer.org
         ServerName wiki.virtual-loup-de-mer.org

```
     ServerAlias wiki.v-l-m.org

     DocumentRoot /data/www/wiki.virtual-loup-de-mer.org/html

     ErrorLog /data/www/wiki.virtual-loup-de-mer.org/logs/error_log
     CustomLog 
```

/data/www/wiki.virtual-loup-de-mer.org/logs/access_log combined

```
     <Directory /data/www/wiki.virtual-loup-de-mer.org>
             Options Indexes Includes
             AllowOverride All
             order allow,deny
             allow from all

             # 2.4: autorisation nécessaire
             <IfModule mod_authz_core.c>
                 Require all granted

                 #
                 # === VERSION DE PHP ===
                 # Conf PHP 5.4 ==> 127.0.5.5
                 # Conf PHP 5.5 ==> 127.0.5.5
                 # Conf PHP 5.6 ==> 127.0.5.6
                 # Conf PHP 7.0 ==> 127.0.7.0
                 <FilesMatch "\.php$">
                         SetHandler "proxy:fcgi://127.0.5.4:9000"
                 </FilesMatch>
             </IfModule>

             DirectoryIndex index.php index.html

     </Directory>

     Alias /stats /data/www/wiki.virtual-loup-de-mer.org/stats
```

</VirtualHost>

**Comment by sbsrouteur** [comment]
https://www.mediawiki.org/wiki/Manual:Errors_and_symptoms#All_pages_have_no_content.2C_but_when_editing_a_page_the_wiki_text_is_there

MediaWiki Errors
All pages have no content, but when editing a page the wiki text is there
Optionally with those error messages:

PHP Warning: preg_replace(): Compilation failed: group name must start with a
  non-digit at offset 4 in /var/www/wiki/htdocs/includes/MagicWord.php
This is caused by a change in PCRE 8.34. You need to downgrade PCRE, or update MediaWiki to version 1.22.1 or newer (see task T60640).

See report: Topic:Rz2zo0m88rrxqrfn and Thread:Project:Support_desk/MediaWiki_don't_work_with_PCRE_8.34_(2)

**Comment by fmicaux** [comment]
Salut,

D'après mes lectures de cette semaine : http://php.net/eol.php

Je ne sais pas pourquoi, mais mercredi, j'ai écrit un script qui 
automatise la compilation-installation-mise en prod de mes Apache 2.4 et 
PHP x.y, et dès jeudi, il y avait une nouvelle 5.5, 5.6 et 5.7... Ca 
marche bien mes petits scripts  !

Dans la bataille, la version de PHP 5.4 est passé de 5.4.39 à 5.4.45.

Je ne vais pas "downgrader" PCRE et ça serait pas mal que le wiki puisse 
tourner sur PHP 5.6 voire 7.0, vue la fin de support de la version 5.4 
(septembre 2015).

Il y a une quotidienne de la base de données.

Qui sait s'y coller ?

J'ai fait une sauvegarde du site en plus des quotidiennes à l'instant.

Je tente ma chance cet après-midi.

François

**Comment by fmicaux** [comment]
Apparement, il manque des plugins / extensions.

J'ai installé "Widgets", mais la suite semble être "Smarty"

==> /var/log/httpd/wiki.virtual-loup-de-mer.org/error_log <==
[Sat Jan 09 17:02:29.839495 2016] [proxy_fcgi:error] [pid 18807:tid 
140364811851520] [client 78.212.154.196:47548] AH01071: Got error 'PHP 
message: PHP Warning: 
require_once(/data/www/wiki.virtual-loup-de-mer.org/mediawiki-1.26.2/extensions/Widgets/smarty/libs/Smarty.class.php): 
failed to open stream: No such file or directory in 
/data/www/wiki.virtual-loup-de-mer.org/mediawiki-1.26.2/extensions/Widgets/Widgets.php 
on line 56\nPHP message: PHP Fatal error:  require_once(): Failed 
opening required 
'/data/www/wiki.virtual-loup-de-mer.org/mediawiki-1.26.2/extensions/Widgets/smarty/libs/Smarty.class.php' 
(include_path='/data/www/wiki.virtual-loup-de-mer.org/mediawiki-1.26.2:/data/www/wiki.virtual-loup-de-mer.org/mediawiki-1.26.2/includes:/data/www/wiki.virtual-loup-de-mer.org/mediawiki-1.26.2/languages:.:/opt/php-fpm-5.6/lib/php') 
in 
/data/www/wiki.virtual-loup-de-mer.org/mediawiki-1.26.2/extensions/Widgets/Widgets.php 
on line 56\n'

La nouvelle version est 'testable" dans wiki.v-l-m.org/new/
Les logs sont accessibles par FTP.

Si quelqu'un prend la suite, me prévenir.
Je dois m'absenter et pourrai regarder de nouveau en soirée, mais pas avant.

François

**Comment by fmicaux** [comment]
Re,

Je ne parviens pas à faire marcher mediawiki 1.26.2 qui m'annonce un 
problème de base de données.

Pas envie de casser la base qui n'a pas l'air en cause dans ce problème 
de preg_replace & pcre.

Trouvé un "contournement" qui consiste à vider le cache en ajoutant au 
four de chaque URL qui retourne une page vide la chose suivante : 
&action=purge

Exemple :

Sur la page 
http://wiki.virtual-loup-de-mer.org/index.php?title=Pr%C3%A9sentation
rappeler l'URL comme ceci : 
http://wiki.virtual-loup-de-mer.org/index.php?title=Pr%C3%A9sentation*&action=purge*

C'est vraiment pas beau et ça ne marche pas pour toutes les pages.

Ce qui est sûr par contre, c'est que je ne vais pas le faire pour toutes 
les pages et qu'il faudrait le faire "au fil de l'eau" tant que le wiki 
n'est pas moté en version compatible avec les versions maintenues de PHP.

Disponibles sur le serveur : la dernière de chaque branche, de 4.4 (via 
cgi/cgid), et via  PHP-FPM : 5.3, 5.4, 5.5, 5.6 et 7.0

J'ai du coups configuré le vhost de vlmwiki en 5.6, et ai fouillé sur 
l'update en v1.26.2, en appliquant "update.php" du répertoire maintenance.

Pour ceux qui accèdent au serveur via FTP, on travaille maintenant dans 
le répertoire mediawiki-1.26.2.

j'ai modifié le LocalSettings.php car il y a des changements dans la 
déclaration des extensions.

Ca a l'air beaucoup mieux, et ça me semble en grande partie migré.

__Reste à faire : problème avec l'extension Widgets, et celles sur les 
Capchas, qui ne chargent pas.___*
*_
  Je laisse les choses là, pour l'instant. Si quelqu'un peut réactiver 
ces choses, ça me va bien.

J'ai fait une sauvegarde du répertoire "de production", et celle de la 
base de donnés se fait toute seule dans 3 heures.

François
