### ISSUE TITLE
Calcul de déplacement pour des TWA "ridicules"

### ISSUE THREAD

**Issue by maitaivw** [v-l-m/vlm#850]
On me soumet depuis qques jours à ce problème: Les calculs faits par qtVlm (et par FT parait-il) sont faux quand le TWA est disons dans le rouge. Je cite:

> On peut facilement illustrer ce que j'ai dit précédemment.
> Un bateau au mouillage (VA=0) avec une polaire de BP5 dans la PSDB 
> Dans un vent d'une 20aine de nd, je lui met un angle de 0.5° ce qui le fait avancer d'une 30aine de mètres d'après l'estime de FT ou QT. 
> Après une vac de 5mn il n'a pas bougé d'un millimètre et VLM donne les mêmes coordonnées. 

Y'a t'il qque chose que les outils ne savent pas et qu'ils devraient savoir dans ce cas?

**Comment by pzia** [comment]
De mémoire, un bateau dont le twa est strictement inférieur à 1 est
considéré à l'ancre, et c'est au tout début du calcul de vac.

**Comment by maitaivw** [comment]
Ah. Donc si TWA < 1 alors BS = 0

Je ne savais pas et ca peut expliquer certaines étrangetés (certains s'amusent à essayer de se rapprocher le plus possible d'un point géographique et donc font ca)

**Comment by pzia** [comment]
https://github.com/v-l-m/vlm/blob/master/moteur/check_user.php

Lignes 22 / 23

**Comment by pzia** [comment]
Ça rend le challenge pour se rapprocher d'un point plus intéressant

**Comment by sbsrouteur** [comment]
cap fixe ^^
