### ISSUE TITLE
Wiki spammers

### ISSUE THREAD

**Issue by maitaivw** [v-l-m/vlm#852]
On a un gros probleme on dirait:

http://wiki.virtual-loup-de-mer.org/index.php?title=Sp%C3%A9cial:Modifications_r%C3%A9centes&limit=500&days=30

**Comment by sbsrouteur** [comment]
Oui on a un problème.

Mais je n'ai pas les clés du serveur host wiki.v-l-m.org. ET je ne suis pas
admin du wiki.

Qui est admin du wiki?
Il faut re-désactiver la création de users.
Voir comment est configuré le/les captcha de création de compte, faire un
MAJ si nécessaire pour un avoir captcha du jour.
Faire le ménage dans la BD.

++

**Comment by sbsrouteur** [comment]
réglé
