### ISSUE TITLE
Round vac start time to nearest minute

### ISSUE THREAD

**Issue by maitaivw** [v-l-m/vlm#855]
Tout est dans le titre, voir https://github.com/v-l-m/vlm/issues/610 pour les détails du pourquoi.

Je veux bien meme faire les modifs, lol.

**Comment by sbsrouteur** [comment]
J'ai clos l'autre, je peux clore celui là ou il y a autre chose à voir avec?

**Comment by maitaivw** [comment]
vi, meme si on sait que si plus de 1000 joueurs ca va se remettre à délirer.

**Comment by sbsrouteur** [comment]
On en reparle quand on a plus de 1000 joueurs ;)

**Comment by farangfrog** [comment]
836 joueurs sur le VDG et ça ne va pas s'arrêter là
et peut-être la C5 qui partira plus ou moins en même temps, 64 inscrits pour l'instant

Faut-il qu'on en reparle ?

**Comment by sbsrouteur** [comment]
à mon sens ça ne va pas délirer, car on va pas avoir des variations
aléatoires comme avant. La vac va durer globalement 300s pour tout le
monde, quelques 301 et quelques 299.
Mais en moyenne ça devrait le faire.

2016-11-03 18:04 GMT+01:00 farangfrog notifications@github.com:
