### ISSUE TITLE
"&" in boat's name , etc

### ISSUE THREAD

**Issue by maitaivw** [v-l-m/vlm#857]
Vous pouvez interdire ça? ca fout la grouille et c'est un bon moyen de bloquer tout vlm

**Comment by sbsrouteur** [comment]
CreatePlayer.php line 78 CheckNonConformity

Note pour savoir ou chercher pour corriger plus tard.

**Comment by maitaivw** [comment]
Et alors?

**Comment by sbsrouteur** [comment]
Et bien le & est vérifié à la création du nom utilisateur. Donc comment est-ce que ça a pu se produire...
Je vais éplucher les logs. Mais quel était l'ID du joueur, ou son nom de boat?

**Comment by maitaivw** [comment]
C'était le 28158, nom du joueur Pytheas1_____gt; sauf que avant que je le change c'était Pytheas1_____&gt;

**Comment by maitaivw** [comment]
cad avec "& g t" à la fin, sans les espaces.

**Comment by pzia** [comment]
Oui, il y a une sanitisation très brutale.
Le > est transformé en &gt; en html. C'est une balise safe.

**Comment by maitaivw** [comment]
Soit le problème venait de là, soit il venait du champ "country" (le drapeau) qui était vide. Ou alors à cause de ca ca me rendait un champ drapeau vide, je ne sais pas. Depuis j'ai rajouté un truc pour ignorer le drapeau dans ce cas mais bon...
Ce que je sais c'est que j'ai modifié le nom du joueur (retiré le caractère >) et aussi mis un flag, le champ était vide. Et après ca plus de plantage dans qtVlm, qui se plantait pour tous les joueurs inscrits à la même course que ce joueur.
