### ISSUE TITLE
quick posting mail : quels sont les destinataires ? qui a les clés du groupe google vlm-news ?

### ISSUE THREAD

**Issue by farangfrog** [v-l-m/vlm#865]
J'ai fait un quick posting, option mail depuis l'interface admin tout à l'heure (http://www.virtual-loup-de-mer.org/admin/post_news.php). D'après http://www.virtual-loup-de-mer.org/admin/news.php, le message est bien enregistré dans la base de donnée et, par un mécanisme que j'ignore, est expédié via le google group vlm-news. J'ai finalement bien reçu le message sur ma boite mail, mais plusieurs autres vlm-istes n'ont rien reçu (maitai par exemple)

Questions : 
- quels sont les membres de ce groupe ? 
- qui a les clés du groupe google pour regarder un peu ce qui se passe dedans ?

**Comment by sbsrouteur** [comment]
Les membre du group news vlm gougoule sont :
[image: Inline image 1]

Je peux te sortir la liste des emails si tu le souhaites.

++

2016-10-26 22:59 GMT+02:00 farangfrog notifications@github.com:

**Comment by farangfrog** [comment]
@sbs je ne vois pas l'image en ligne...

Je veux bien la liste des emails, mais après, je ne vois pas bien comment envoyer à tout le monde. Comment faire ça à partir d'une adresse virtual-loup-de-mer.org, par exemple noreply@virtual-loup-de-mer.org ?

**Comment by sbsrouteur** [comment]
Bon je sais faire une mailing list des 8885 joueurs VLM. Puis faire un
sendmail qui renvoie ton message à tous ces gens là...

feu ?!?!?

2016-10-27 20:08 GMT+02:00 farangfrog notifications@github.com:

**Comment by farangfrog** [comment]
Cool. Je t'envoie le texte du message par email.

**Comment by sbsrouteur** [comment]
Bon il va falloir que je mettre ça dnas un script car par coup de 8885 destinataire ça ne va pas passer. Je me penche sur la question ce soir.

++

**Comment by sbsrouteur** [comment]
j'ai les clé du groupe.

**Comment by farangfrog** [comment]
tu es puissant !

**Comment by farangfrog** [comment]
sbs, tu as pu voir pour le script ?

**Comment by sbsrouteur** [comment]
non pas encore hier soir j'ai miséré sur jvlm. Mais ça va avoir lieu ce week-end. Le script est simple je veux juste le tester un peu avant d'envoyer

**Comment by farangfrog** [comment]
Ok, cool.

**Comment by sbsrouteur** [comment]
@farangfrog : tu as du recevoir (ou va recevoir dans les prochaines minutes) le mail pour le VDG.

J'ai fait quelques modifs mineures pour aider à passer les anti-spam (mais c'est pas gagné). Peux tu regarder si j'ai rien moisi au passage stp.

**Comment by farangfrog** [comment]
Merci sbs, bien reçu. Y a juste le lien vers le store android dans la version française qui a zappé, mais ce n'est pas dramatique

**Comment by sbsrouteur** [comment]
fixed...

Ca passe chez gmail, free, j'enverrai bien ça maintenant comme ça ....

**Comment by farangfrog** [comment]
C'est bon pour moi

**Comment by sbsrouteur** [comment]
parti...

**Comment by farangfrog** [comment]
Merci sbs
