### ISSUE TITLE
Salade de divs dans la mise en page

### ISSUE THREAD

**Issue by sbsrouteur** [v-l-m/vlm#867]
Suite au merge d'hier soir, il n'y plus d'écran de settings et les onglets de nav du tableau de contrôle sont tous mélanngés.

Peux tu remettre d'aplomb et me faire une PR stp?

**Comment by ChrisCatta** [comment]
Je viens de vérifier ça roule chez moi 
par contre j'ai changer l'entete de la modal pref ce sera pour un futur commit

**Comment by sbsrouteur** [comment]
Non ca ne fonctionne pas. Dans le principe le contenu de ce que tu as dans ortho est déplacé dans VMG et VBVMG en fonction du tab actif (le JS gère ça).
Donc si tu n'as rien dans ortho ou si tu as des truc dans les autres ça met la grouille
.
De plus avant en cliquant sur le tab ça le sélectionnait. Ca ne le fait plus.

++

**Comment by ChrisCatta** [comment]
Ah  j'ai bien vu qu'au debut y avait rien dans VMG et VBVMG ok je vais regarder

**Comment by ChrisCatta** [comment]
Bon j'ai remis comme au debut juste une row avec le bouton mais quand je test j'ai plus rien dans la tab

**Comment by ChrisCatta** [comment]
Y a un autre probleme, qd tu as clique sur un onglet, tu peux plus y revenir je comprend pas bien ce qu'il ce passe

**Comment by ChrisCatta** [comment]
Bon y avait la fermeture de `</nav>` qui etait plus au bon endroit mais ça marche toujours pas

**Comment by ChrisCatta** [comment]
Pourquoi tu as mis de simple guillemets dans la tab pilot?? c'est normal?

**Comment by ChrisCatta** [comment]
Puisque les tab ortho/VMG/VBVMG sont les mêmes, je te propose de faire un onglet navigation par exemple avec trois boutons pour les réglages ortho/Vmg/vbvmg
qu'en pense tu?

**Comment by sbsrouteur** [comment]
On essaye d'avoir une version à mettre sur neptune pour dimanche soir?

2016-10-27 11:34 GMT+02:00 St. B. sbarthes@gmail.com:

**Comment by sbsrouteur** [comment]
simple ou double c'est pareil (normalement). donc ça dépend de mon humeur.

**Comment by sbsrouteur** [comment]
la modal pref ne fonctionne pas du tout chez moi. Ecran noir puis plus rien
