### ISSUE TITLE
Fonctions à ajouter dans le dialogue de préférence

### ISSUE THREAD

**Issue by sbsrouteur** [v-l-m/vlm#873]
[X] un tab pour les prefs joueurs et un tab pour les prefs bateau
[X] les prefs joueurs comme dans l'actuelle page VLM
[X] une combo de sélection de la langue elle n'est pas venue avec la ligne ci-dessus
[X ] Sauvegarde des préférences joueur

**Comment by ChrisCatta** [comment]
Tu veux que le bouton pref actuel ouvre la modale avec 2 onglets?

**Comment by sbsrouteur** [comment]
oui

2016-10-30 5:19 GMT+01:00 ChrisCatta notifications@github.com:
