### ISSUE TITLE
Amélioration dialogue settings

### ISSUE THREAD

**Issue by sbsrouteur** [v-l-m/vlm#874]
Remplacer le select de drapeau par un dropdown BS et mettre dedans 1 ligne avec le nom du drapeau et l'image du drapeau.

Je remettrai en place le remplissage dynamique de cette dropdown, une fois que j'aurais un modèle.

**Comment by ChrisCatta** [comment]
c'est pas la peine de faire un DD pour une ligne remplie dynamiquement non??
Un input text devrait suffire

**Comment by sbsrouteur** [comment]
fixed
