### ISSUE TITLE
discordance entre angle instrument et météo??

### ISSUE THREAD

**Issue by ChrisCatta** [v-l-m/vlm#879]
Il me semble que l'angle affiché dans les instruments et l'angle sur la carte par rapport à la météo n'est pas bon
voir figure çi jointe
![pb angle ou meteo](https://cloud.githubusercontent.com/assets/22868122/19845200/8db4e81c-9f45-11e6-9a28-3dee04828373.jpg)
bon les fleches de vent son petites mais on est pas a 80° du vent!!

**Comment by sbsrouteur** [comment]
Les instruments sont cohérents, vent à 4° cap au 356 donc aux arrondis près on 80° au vent. En revanche les vents sur la carte sont au 34°.  N'aurais tu pas par hasard ce gener d'affichage le matin quand tu regarde sur la page que tu as chargé la veille?

C'est une fonction manquante/bug les gribs ne rechargent pas après les MAJs.

**Comment by ChrisCatta** [comment]
Slt refais le test ce matin apres chargement de la météo vérification sur qtvlm
![pb angle ou meteo1](https://cloud.githubusercontent.com/assets/22868122/19955729/1584f0ec-a195-11e6-8ab7-bfa6f3a473a6.jpg)
