### ISSUE TITLE
Nom bateau??

### ISSUE THREAD

**Issue by ChrisCatta** [v-l-m/vlm#886]
J'ai remarqué un truc bizarre sur la V2 a l'affichage y "d'arrêt" qui dépasse des autre et ce n'est pas un nom de joueur
![affichage vlm2](https://cloud.githubusercontent.com/assets/22868122/19915772/b651748a-a0c5-11e6-8a6c-77dea4ff6c41.jpg)

**Comment by sbsrouteur** [comment]
c'est bête mais c'est un nom de bateau sensiblement plus long que les autres : 
 (#15329) omonradoooo   cailloux, cailloux, quinze minutes d'arrêt

:)
