### ISSUE TITLE
Affichage des coordonnées bouées des portes

### ISSUE THREAD

**Issue by ChrisCatta** [v-l-m/vlm#908]
Je trouve que l'affichage des coordonnées des portes sur la map surcharge inutilement l'affichage on pourrai les avoir juste au survol de la bouée.
On avait parlé aussi de faire arriver la ligne sur le bout du trais horizontal de la bouée pour une meilleure précision

**Comment by sbsrouteur** [comment]
Oui le texte est trop gros quand on est loin. Ptet qu'on pourrait ne l'afficher qu'à partir d'un certain niveau de zoom.
Oui pour a ligne qui arrive au milieu des bouées, j'ai essayé mais il faut un offset de l'image négatif et ça ne semble pas fonctionner. Donc deux options pour ça : 
  [ ]Tester une valeur d'offset qui va bien :  voir vlmboat.js ligne 491
  [X] refaire l'image en doublant sans hauteur avec du vide en dessous pour que le milieu de l'image soit le point d'arrivée de la ligne. et Mettre  à jour la taille de l'image dans le fichier vlmboat.js ligne 489.

La solution 2 est plutot triviale,

**Comment by sbsrouteur** [comment]
coords in popup
