### ISSUE TITLE
Ranking button not accessible on small screen

### ISSUE THREAD

**Issue by sbsrouteur** [v-l-m/vlm#917]
Des divs recouvrent le bouton, donc on ne peut pas afficher le classement.

**Comment by sbsrouteur** [comment]
Ok, le bouton ranking fonctionne et on abien le classement.

mais si on "déplie" un concurrent dans la liste on a plein de lignes blanches....

**Comment by ChrisCatta** [comment]
ok je vais test pour voir mais faut que j'ai un opposant :-)
