### ISSUE TITLE
Pb Affichages popups

### ISSUE THREAD

**Issue by sbsrouteur** [v-l-m/vlm#918]
Les popup flottante position et affichage restent coincées dans le bandeau sur petit écran

**Comment by ChrisCatta** [comment]
marche bien chez moi tu as recupéré le js ?
jquery.ui.touch-punch.js

**Comment by sbsrouteur** [comment]
Chez moi en mode tel, on voit un div par dessus les boutons:
![capture](https://cloud.githubusercontent.com/assets/11095871/20430278/b763acaa-ad93-11e6-90e2-6ab0c6de9924.PNG)
