### ISSUE TITLE
salade de ZOrder entre le classement et la popup de position

### ISSUE THREAD

**Issue by sbsrouteur** [v-l-m/vlm#925]
Il y a comme un mélange ....

![image](https://cloud.githubusercontent.com/assets/11095871/20579488/2ae16ba8-b1cd-11e6-88ee-694fad61bc30.png)

**Comment by ChrisCatta** [comment]
je vais voir pq ça fait ca 
Bon c'est uniquement sur la tab classement pour les autres la modale est dessous
Par contre on la garde sur toute les autres ou pas??
