### ISSUE TITLE
Alignement bizarre bouton de login

### ISSUE THREAD

**Issue by sbsrouteur** [v-l-m/vlm#929]
![image](https://cloud.githubusercontent.com/assets/11095871/20634904/190951e0-b356-11e6-80ed-888d548e9a31.png)

On devrait avoir la même hauteur pour les deux boutons et pas un bitmap écrasé entre les deux.

**Comment by ChrisCatta** [comment]
Y 'en a un qui est un DD et l'autre un btn dont la taille est reglée auto par la taille du txt et entre les 2 c'est un glyphicon qui est traitée comme du text
