### ISSUE TITLE
Alignement discutable

### ISSUE THREAD

**Issue by sbsrouteur** [v-l-m/vlm#931]
Sur écran large on a ça : 
![image](https://cloud.githubusercontent.com/assets/11095871/20634942/acf0b826-b356-11e6-840e-8e3fa67e25ad.png)

**Comment by ChrisCatta** [comment]
J'avais reglé comme ça pour que ça s'empile bien sur tel mais on peut changer

**Comment by sbsrouteur** [comment]
Si on peut garder un alignement correct sur tel et que ce soit plus lisible sur grand écran :)
