### ISSUE TITLE
themes

### ISSUE THREAD

**Issue by sbsrouteur** [v-l-m/vlm#932]
Le theme pistache ne fonctionne plus chez moi et le vert jaune n'est pas reporté sur la popup d'outils:
![image](https://cloud.githubusercontent.com/assets/11095871/20634967/f9617754-b356-11e6-814a-e70ab593ca48.png)

**Comment by ChrisCatta** [comment]
pfff c'est quoi ça??? je comprend pas ou les fichiers sont passés à moitié avec ma P... de connexion de M...
y a des fichiers images qui ne sont pas passés ou que tu as pas recupérés

**Comment by ChrisCatta** [comment]
tu peux fermer ce ticket non?
