### ISSUE TITLE
Pb Alignement badge pilototo

### ISSUE THREAD

**Issue by sbsrouteur** [v-l-m/vlm#934]
![image](https://cloud.githubusercontent.com/assets/11095871/20640279/becd87ee-b3d9-11e6-97f4-8e1738a61339.png)

(au moins en anglais)

**Comment by ChrisCatta** [comment]
Bon moi il était pas la mais je te propose de le mettre au dessus de l'icone
![badge pilot](https://cloud.githubusercontent.com/assets/22868122/20645519/f852a038-b471-11e6-98f1-975f74e0e7c0.jpg)

**Comment by sbsrouteur** [comment]
fixed 9cac0efc67e5da99b9a6ca05320c690e443cb86a
