### ISSUE TITLE
VLM2 is broken for IE

### ISSUE THREAD

**Issue by sbsrouteur** [v-l-m/vlm#936]
Hangs loading...

**Comment by ChrisCatta** [comment]
oui je viens de tester aussi ..marche po :-(

**Comment by sbsrouteur** [comment]
Je viens d'ouvrir un ticket sur le sujet chez footables.
https://github.com/fooplugins/FooTable/issues/563

**Comment by sbsrouteur** [comment]
Fixed with https://github.com/v-l-m/vlm/commit/65cec05c89a0110445c42ca6725393d6e44c75db
