### ISSUE TITLE
Cant upload custom polars for our catamaran

### ISSUE THREAD

**Issue by Kaitoro** [v-l-m/vlm#950]
Great work on qtVlm!

A fantastic program!

However, I cannot upload our polars into “Boat(s) settings” for our catamaran that I have created using the weather routing plugin for OpenCPN. I have them in the polars folder for qtVlm. See below - 

qtVlmRejectPOLAR.png
![qtvlmrejectpolar](https://cloud.githubusercontent.com/assets/25182674/22034340/38be70f2-dca9-11e6-8e8c-213a9f61f25e.png)

I can however import them into the polar plugin program for OpenCPN and run the weather routing plugin for OpenCPN - 

OpenCPNRouting.png
![opencpnrouting](https://cloud.githubusercontent.com/assets/25182674/22034370/4f2cf214-dca9-11e6-8a45-c90f43443ec8.png)

I can run your program using one of your supplied polars. Great!

I really like the setting for motoring as that is sometimes the default. For instance trying to “sail” today from the Solomon Islands where our boat is currently back to Cairns in Australia. Motoring the whole way. Painful.

I attach this polar file and the boat file created, tho’ this doesn’t look as if it has the boat details in it.

I would appreciate any hints on how to make your program acccept our vessel's polars.

Tx,

Jeff.

early 2009 iMac running OS 10.11.6
OpenCPN 4.4.0 with latest plugins
qtVlm 5.4-5

Jeff Boyd, CCFPEM ABEM IFMGA ACMG 
Emergency Physician, Mountain Guide, 
PO Box 400, Banff. AB  
Canada.  T1L 1A5
E-mail:  <jbboat@telus.net>
Tf:     (403)762-4974(H)

SY Kaitoro
VJN4817

I cannot upload the polar file to this website as it won't accept a .pol file. I have zipped it here - 

[KaitoroVeryBest.pol.zip](https://github.com/v-l-m/vlm/files/712015/KaitoroVeryBest.pol.zip)

[KaitoroVeryBest.xml.zip](https://github.com/v-l-m/vlm/files/712022/KaitoroVeryBest.xml.zip)

**Comment by oxygen77** [comment]
Hello Kaitoro,

Thx for your comments and support on our jov on qtVlm.

First your are not posting in the right place, your are in the VLM (Virtual Loup de Mer) list which is dedicated to the game: www.v-l-m.org

If you want to reach qtVlm dev please send email to support@meltmemus.com

But you are lucky as we (the dev of qtVlm) are also on this list :)

For your question on polar, I'm not fully aware of ocpn process to generate polar but on our side we are expecting pol files to use tabulation as separator, and comma ( ; ) as separator for csv files. So renaming your file KaitoroVeryBest.pol to KaitoroVeryBest.csv allowed me to load/import the polar in qtVlm

Regards,

Chris

----- Mail original -----
De: "Kaitoro" <notifications@github.com>
À: "v-l-m/vlm" <vlm@noreply.github.com>
Cc: "Subscribed" <subscribed@noreply.github.com>
Envoyé: Mardi 17 Janvier 2017 19:47:50
Objet: [v-l-m/vlm] Cant upload custom polars for our catamaran (#950)



Great work on qtVlm! 

A fantastic program! 

However, I cannot upload our polars into “Boat(s) settings” for our catamaran that I have created using the weather routing plugin for OpenCPN. I have them in the polars folder for qtVlm. See below - 

qtVlmRejectPOLAR.png 
qtvlmrejectpolar

I can however import them into the polar plugin program for OpenCPN and run the weather routing plugin for OpenCPN - 

OpenCPNRouting.png 
opencpnrouting

I can run your program using one of your supplied polars. Great! 

I really like the setting for motoring as that is sometimes the default. For instance trying to “sail” today from the Solomon Islands where our boat is currently back to Cairns in Australia. Motoring the whole way. Painful. 

I attach this polar file and the boat file created, tho’ this doesn’t look as if it has the boat details in it. 

I would appreciate any hints on how to make your program acccept our vessel's polars. 

Tx, 

Jeff. 

early 2009 iMac running OS 10.11.6 
OpenCPN 4.4.0 with latest plugins 
qtVlm 5.4-5 

Jeff Boyd, CCFPEM ABEM IFMGA ACMG 
Emergency Physician, Mountain Guide, 
PO Box 400, Banff. AB 
Canada. T1L 1A5 
E-mail: jbboat@telus.net 
Tf: (403)762-4974(H) 

SY Kaitoro 
VJN4817 

I cannot upload the polar file to this website as it won't accept a .pol file. I have zipped it here - 

KaitoroVeryBest.pol.zip 

KaitoroVeryBest.xml.zip

**Comment by Kaitoro** [comment]
Thank you so much Chris,

I had tried saving my polars as .csv files using the OpenCPN polar plugin but qtVlm would not upload them. Messed around in Excel but that didn’t work either.

But, renaming the .pol file as a .csv file worked.

Great!


Jeff.

Jeff Boyd, CCFPEM ABEM IFMGA ACMG 
Emergency Physician, Mountain Guide, 
PO Box 400, Banff. AB  
Canada.  T1L 1A5
E-mail:  <zmtndoc@telus.net>
Tf:     (403)762-4974(H)

SY Kaitoro
VJN4817
