### ISSUE TITLE
VLM inaccessible depuis environ 20h00 UTC+1

### ISSUE THREAD

**Issue by farangfrog** [v-l-m/vlm#951]
"Could not connect : Too many connections"

**Comment by sbsrouteur** [comment]
fixed. La partitition var dans laquelle il y a logs systéme a décidée qu'elle était pleine. J'ai agrandi un peu.
Je vais regarder s'il n'y a pas un peu de ménage a faire.

**Comment by farangfrog** [comment]
Merci !
