### ISSUE TITLE
Meteo map change button gets away sometimes

### ISSUE THREAD

**Issue by sbsrouteur** [v-l-m/vlm#954]
On smaller screens, the grib date selection is hidden by the menu bar.

Fix div layout between the menu bar and the map area

full description here : 
http://www.virtual-winds.org/forum/index.php?/topic/7273-lmnh-bateaux-manchots-permanents/&do=findComment&comment=274381

**Comment by ChrisCatta** [comment]
Oui j'ai vu j'y réfléchis mais pas évident ça vient de la NavBar qui passe par dessus tout le reste
Il faudrait que la map ce cale dessous quelle que soit la hauteur de celle ci mais pour le moment pas trouvé la soluce
La Map quand a elle est en absolu et a 75px du top il faut que je fouille sur OpenLayer pour voir comment on peut modifier, 
pas gagné...

**Comment by sbsrouteur** [comment]
oui, il y a un bug dans la layout, pour que le menu passe sur la zone de map. Je te laisse regarder.

Ou alors, on met le plus de la meteo ailleurs et ca permet de contourner ce menu qui change de taille en fonction de l'écran

**Comment by ChrisCatta** [comment]
il est definis ou le + de la météo et celui du zoom aussi même combat mais moins indispensable
Il faut peut etre revoir ce bouton météo avec toutes le remarques sur la manière d’incrémenter de 1h si tu veux la météo dans 24 ou 48 h je te laisse compter le nombre de fois ou tu dois cliquer!!
La Navbar passe forcement au dessus du reste définition de bootstrap donc si elle peut s'agrandir (dimension de l'ecran ou longueur du nom de la course) ça passe obligatoirement sur la map
je n'ai pas mis du tout le nez dans le fonctionnement de la map et des boutons qui sont dessus, donc j'ai du mal a savoir quoi modifier

**Comment by ChrisCatta** [comment]
voila ce que je te propose, de descendre le bouton du grib et de l'echelle (celui de gauche) de 200px ce qui laisse de la marge a la NavBar
Reste a voir le moyen de regler le grib plus facilement
il faut aussi mettre les accents normaux dans le fichier local fr

**Comment by pzia** [comment]
le widget de règlage de l'offset météo utilise Openlayers.
Vu votre implémentation actuelle, il est probablement plus simple et plus
pertinent de réécrire des contrôles sans OpenLayer pour à la fois vous
facilier la maintenance et l'intégration.
