### ISSUE TITLE
Transition VLM to SSL

### ISSUE THREAD

**Issue by sbsrouteur** [v-l-m/vlm#960]
[X] Add SSL cert and accept ssl connections to VLM
[X ] Add redirect rule so that JVLM is accessed via  SSL
[X ] Add redirect rule in apache so that all requests to vlm end-up as ssl
[ X] Configure SSL on testing for tools to prepare

wiki de procédure : https://github.com/v-l-m/vlm/wiki/SSL_VLM

**Comment by oxygen77** [comment]
quel est l'impact pour les outils externes ? Je viens de faire un test en connectant qtVlm sur testing (http://testing.v-l-m.org) rien de changé, tout fonctionne en tout cas

Chris

**Comment by sbsrouteur** [comment]
Rien n'a changé parfait. La modif que j.ai fait est mineure et n'avait pas pour intention de casser l'existant. 
A moyen terme je vais mettre un certificat ssl et forcer les connexions à jvlm en ssl. Ca n'aura pas d'impact direct sur les outils jusqu.a ce qu'on décide de passer tout vlm en https. Et ca va impacter les outils suivant comment ils supportent le redirection. 

Apparemment Maitai avait l'air de dire qu'avec iOS et Android ça allait poser probleme.

**Comment by oxygen77** [comment]
une fois l'activation du https ça risque en effet de poser pb sur ces plateforme à etudier de notre côté dès que ce sera sur testing

**Comment by sbsrouteur** [comment]
Bon y a du SSL sur testing. C'est pas completement propre, pour le chat en particulier, mais vous pouvez-y accéder.

J'ai pas encore activé le redirect forcé HTTP->HTTPS. J'attend vos premiers retours sur le sujet.

**Comment by ChrisCatta** [comment]
Pour moi aucun changement

**Comment by ylafon** [comment]
Au passage:
https://www.ssllabs.com/ssltest/analyze.html?d=testing.v-l-m.org
https://wiki.mozilla.org/Security/Server_Side_TLS

**Comment by sbsrouteur** [comment]
Au cas ou ce n'était pas suffisament clair tout est accessible en SSL sur testing, donc vous pouvez essayer les outils en SSL ou comme avant.

**Comment by sbsrouteur** [comment]
https://www.ssllabs.com/ssltest/analyze.html?d=v-l-m.org

Score : A 👍
