### ISSUE TITLE
Nouvelle Barre de menu - Pb dialogue settings

### ISSUE THREAD

**Issue by sbsrouteur** [v-l-m/vlm#971]
Le dialogue des settings "depasse fortement" en mode téléphone.

**Comment by ChrisCatta** [comment]
ben j'ai pas de probleme de ce genre 
![setting](https://cloud.githubusercontent.com/assets/22868122/24897533/e79f93d2-1ea1-11e7-8be6-0832e324e873.png)

**Comment by sbsrouteur** [comment]
Ok artéfact du debugger opera, pas pu reproduire le problème sur mon tel.
