### ISSUE TITLE
Nouvelle barre de menu - Alignement général

### ISSUE THREAD

**Issue by sbsrouteur** [v-l-m/vlm#972]
J'aime bien ce nouveau layout, mais les boutons collés à droite quand on a un grand écran, ça fait vraiment bizarre....

**Comment by ChrisCatta** [comment]
Bon en fait je croyais avoir envoé les modifs pour la barre a gauche mais y des conflits voir #974

**Comment by sbsrouteur** [comment]
J'ai résolu les conflits et mis à jour sur testing avec la nouvelle barre mais :
- Sur grand écran boutons à droite, onglets de navigations a droite -=> bizarre
- La drop down des bateau apparait sur 2 colonnes
- Sur tel (si on n'est pas loggé), on a la dropdown de sélection du bateau visible
- On a encore le bouton stop rond.
![navbar1](https://cloud.githubusercontent.com/assets/11095871/24926902/6eb77122-1efd-11e7-94d1-d7d445bf638d.PNG)
![img_3197](https://cloud.githubusercontent.com/assets/11095871/24926909/76a91804-1efd-11e7-87bd-2e8160ff2484.PNG)

**Comment by ChrisCatta** [comment]
rectifié dans le PR #979  sauf le bouton bateau mais j'ai ouvert un ticket a ce sujet

**Comment by sbsrouteur** [comment]
Sur la version actuelle de la nouvelle navbar sur testing, avec IE et un écran large, le triangle vers le bas de sélection de la langue trouve le moyen de ne pas être à coté du drapeau.
