### ISSUE TITLE
Popup RaceInfo : Affichage des polaires

### ISSUE THREAD

**Issue by sbsrouteur** [v-l-m/vlm#973]
J'ai mis à jour index.html pour afficher dynamiquement les polaires en fonction du type de bateau. Mais il manque visiblement un bout de style pour que les images s'affichent dans la boite de dialogue.

Peux tu regarder ça?

PS : c'est sur la branche master ça :P

**Comment by ChrisCatta** [comment]
regarde le #☺978 si ça résout le pb comme tu veux
mais tu fais pas le slideshow comme bootstrap donc c'est pas evident
j'ai essayé a la manière bootstrap mais j'ai le problème de mettre "active" sur la première image donc le slideshow ne démarre pas

**Comment by sbsrouteur** [comment]
On avait progressé, mais tout est reparti en vrille sur la V9. Je ne sais pas quel merge a perdu ta version qui allait presque bien.

**Comment by ChrisCatta** [comment]
je crois avoir trouvé, y avait un espace devant .slideshow la ça devrait aller

**Comment by sbsrouteur** [comment]
Bon c'est mieux mais encore pas ça. On a toutes les polaires visibles sur la droite.

**Comment by ChrisCatta** [comment]
chez moi ça marche comme il faut une fois que la class .slideshow est opérationnelle elle cache l'overflow

**Comment by ChrisCatta** [comment]
![slideshow-apres](https://cloud.githubusercontent.com/assets/22868122/25163496/7c862aba-24d3-11e7-89e9-452079c39dab.png)
![slideshow-avantpng](https://cloud.githubusercontent.com/assets/22868122/25163495/7c839be2-24d3-11e7-8c07-3f2cca8a6bef.png)
