### ISSUE TITLE
Affichage infos permanentes(tryptique)

### ISSUE THREAD

**Issue by ChrisCatta** [v-l-m/vlm#980]
Est ce qu'un truc comme ça avec les badge ça t’irait pour afficher les infos dans la navbar
Bon la y a pas de mise ne forme ni rien mais sur le principe?
![infos](https://cloud.githubusercontent.com/assets/22868122/24964698/a69cf9f6-1faa-11e7-8e8b-202a0f97264c.png)

**Comment by sbsrouteur** [comment]
Sur le principe oui, mais je verrai plutôt cap et vitesse bateau, cap et vitesse vent avec chacun une icône d'identification.
Le système de badge est pas mal.

Une fois qu'on aura mis les données en place, on demandera à silver de nous faire des icones sorties de derrière les fagots

**Comment by ChrisCatta** [comment]
une idée
![badgeinfo-360](https://cloud.githubusercontent.com/assets/22868122/24992578/d2296778-202a-11e7-945c-4b1ec2a7b989.png)
![badgeinfo-768](https://cloud.githubusercontent.com/assets/22868122/24992577/d22689d6-202a-11e7-9fff-22ccd8b7abf1.png)
![badgeinfo-1024](https://cloud.githubusercontent.com/assets/22868122/24992579/d22f2316-202a-11e7-942d-beb9f8a6cea7.png)
qu'est ce que tu en pense?

**Comment by sbsrouteur** [comment]
Que c'est pas mal, (même si je ne le voyais pas comme ça)
Par contre on a deux fois le temps en course affiché

**Comment by ChrisCatta** [comment]
ben avant d'enlever l'autre je voulais ton avis

**Comment by ChrisCatta** [comment]
regarde un peu si ça te vas (je trouve pas ça terrible)
![badgeinfo](https://cloud.githubusercontent.com/assets/22868122/25063539/6b8c62b0-21ef-11e7-942e-965a719e5936.png)

**Comment by sbsrouteur** [comment]
Non pas top, ca augment l'épaisseur de la navbar qui reste à moitié vide par ailleurs.

**Comment by ChrisCatta** [comment]
on fait quoi alors??

**Comment by sbsrouteur** [comment]
on fait appel à a un ami ou au public

**Comment by ChrisCatta** [comment]
je pense que si on les gardes a gauche contre le logo ça passe
![badgeinfo2](https://cloud.githubusercontent.com/assets/22868122/25065971/404a5bce-2222-11e7-9ac9-a8336652a892.png)
![badgeinfo3](https://cloud.githubusercontent.com/assets/22868122/25065988/a64c5a26-2222-11e7-8f48-f07e77938f30.png)

**Comment by sbsrouteur** [comment]
Et en dessous de 1024, ça donne quoi ?
On peut enlever le nom du joueur la aussi.

**Comment by ChrisCatta** [comment]
![badgeinfo3-ouvert](https://cloud.githubusercontent.com/assets/22868122/25068560/01f0cd56-2270-11e7-82d0-5dc6f8695ed0.png)
la c'est deja 768px de large je rajoute la version ouverte

**Comment by ChrisCatta** [comment]
en 360
![badgeinfo360](https://cloud.githubusercontent.com/assets/22868122/25068617/00399aea-2272-11e7-9eaf-38b34d839d02.png)
![badgeinfo-360ouvert](https://cloud.githubusercontent.com/assets/22868122/25068616/0038d5c4-2272-11e7-8548-956101d9ea33.png)

**Comment by sbsrouteur** [comment]
Je pense qu'on va laisser comme ça (pour le moment). Même si c'est
frustrant de ne pas arriver à faire rentrer tout ça. Dans toutes les
configurations.

Je joue principalement sur "grand" écran donc y a toujours la place, par
contre quand je suis sur mon téléphone, je passe mon temps à ouvrir et
fermer des panneaux pour voir. C'est pénible, mais ça reste jouable.

++

**Comment by sbsrouteur** [comment]
J'ai mis la fonte en superscript pour que ça reste sur 3 lignes, mais sur tel ça ne fonctionne pas (IOs)

**Comment by ChrisCatta** [comment]
fait #988 je crois
