### ISSUE TITLE
Infos polaire

### ISSUE THREAD

**Issue by ChrisCatta** [v-l-m/vlm#981]
voila ce que je propose
![polaire](https://cloud.githubusercontent.com/assets/22868122/24993852/d2ae0784-2030-11e7-915e-32aacb262805.png)
dis moi ce que tu pense...

**Comment by sbsrouteur** [comment]
Oui bien sur parfait.
J'aime moyen le badge pour la durée de vacation.
Est-ce qu'on a un up/down en standard dans bootstrap, ou il faut se le
palucher à la main ça aussi?

**Comment by ChrisCatta** [comment]
pour le badge tu verrais quoi?
on peut l'agrandir ou mettre un peu de color
pour le up/down c'est pour le nb de vac je l'ai rajouté apres ça existe lol type="number"

**Comment by ChrisCatta** [comment]
pour le badge tu verrais quoi?
on peut l'agrandir ou mettre un peu de color
pour le up/down c'est pour le nb de vac je l'ai rajouté apres ça existe lol type="number"
